### ISSUE TITLE
Install failure on sampling-heap-profiler.cc

### ISSUE THREAD

**Issue by GradedJestRisk** [1024pix/pix#1040]
on branch master, `npm run configure` exits with the following error message

`ci:api ] make: Entering directory 'pix/api/node_modules/heap-profile/build' [ci:api ] CXX(target) Release/obj.target/sampling_heap_profiler/bindings/sampling-heap-profiler.o [ci:api ] ../bindings/sampling-heap-profiler.cc: In function ‘v8::Local<v8::Value> TranslateAllocationProfile(v8::AllocationProfile::Node*)’: [ci:api ] ../bindings/sampling-heap-profiler.cc:27:15: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>&)’ [ci:api ] node->name);`

I found no related issue in  [sampling-heap-profiler repository](https://github.com/v8/sampling-heap-profiler/issues)

Config
Node v13.6.0 - npm 6.13.4
Linux 5.3.0-28-generic #30~18.04.1-Ubuntu

**Comment by jonathanperret** [comment]
Please make sure to use the Node.js (v12.4.1) and npm (6.13.4) versions mentioned in `README.md`.

**Comment by GradedJestRisk** [comment]
I already use the version you mention, they are enforced by npm install

**Comment by jonathanperret** [comment]
Your initial comment above did mention `Node v13.6.0` though 😉 

I don't know what to tell you, we build daily on Linux so apart from a Node.js version mismatch I don't see what could be causing the failure of the installation of `heap-profile`. Did you try to `npm install heap-profile@0.4.0` in an empty project?

**Comment by GradedJestRisk** [comment]
Oups, sorry for that, I will try it again..

**Comment by GradedJestRisk** [comment]
I tried again using nvm, but version 12.4.1 is not available(available  v12.3.1 =>  v12.4.0)
It's not even listed in [official releases](https://nodejs.org/en/download/releases/)

**Comment by jonathanperret** [comment]
I made a mistake copying the number from `README.md`, you need version `v12.14.1` not `v12.4.1`, sorry.

**Comment by jonathanperret** [comment]
Closing this as it works with the right Node.js version as far as we know. Feel free to comment if the issue still happens.

**Comment by GradedJestRisk** [comment]
I switched to 12.14.1 and the original error doesn't happen anymore, cool !

I've got another error, maybe related to environment variables (ERR_INVALID_URL)
As README.md seems to indicate, such an error may be expected as long as  environment variables are not configured.
As I'll join the team next week, you can keep this issue closed.

**README.md**
```
3/ Configurer les variables d'environnement dans le fichier `pix/api/.env`
Pour récupérer les différents identifiants / clés de connexion, s'adresser à un membre de [l'équipe PIX](https://github.com/1024pix/pix/graphs/contributors).
```

**Logs**
```
[test:api    ] > pix-api@2.111.0 db:delete pix/api
[test:api    ] > node scripts/database/drop-database
[test:api    ] 
[test:api    ] internal/url.js:243
[test:api    ]   throw new ERR_INVALID_URL(input);
[test:api    ]   ^
[test:api    ] 
[test:api    ] TypeError [ERR_INVALID_URL]: Invalid URL: undefined
[test:api    ]     at onParseError (internal/url.js:243:9)
[test:api    ]     at new URL (internal/url.js:319:5)
[test:api    ]     at Object.<anonymous> (/pix/api/scripts/database/drop-database.js:7:13)
[test:api    ]     at Module._compile (internal/modules/cjs/loader.js:955:30)
[test:api    ]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
[test:api    ]     at Module.load (internal/modules/cjs/loader.js:811:32)
[test:api    ]     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
[test:api    ]     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[test:api    ]     at internal/main/run_main_module.js:17:11 {
[test:api    ]   input: 'undefined',
[test:api    ]   code: 'ERR_INVALID_URL'
[test:api    ] }

```
