### ISSUE TITLE
Testing: état de l'art Pix

### ISSUE THREAD

**Issue by octo-pito** [1024pix/pix#1321]
Qu'est-ce que l'on teste, chez Pix, dans un test:
- unitaire;
- integration;
- acceptance;
- end to end ?

Point d'étape prévu en groupe mardi 28 14h.

**Comment by jbuget** [comment]
Ma vision dev sénior sur Pix (qu'il faut très certainement remettre au goût du jour) : 


## Front / apps Ember

Les choix ci-dessous respectent [les recommandations d'Ember](https://guides.emberjs.com/release/testing/test-types/) :

- **route** → **acceptance** pour navigation/action/gestion du store ou unit (pour computed properties ou méthodes internes simples)
- **controller** → **unit**
- **components / templates** → **integ** ou unit (si computed ou méthode simple)
- **models** → **unit**
- autres (serializers, adapters, helpers, authenticators, etc.) → unit

## Back / app Hapi.js

- application/**route** → **integ** avec test-helper/fake-server
- application/**controller** → **unit**
- **usecase** → **unit**
- **domain/*** → **unit** exclusivement !
- infra/**repo** → **integ** + Bookshelf / Knex
- infra/**serializer**  **unit**
- infra/data/**airtable** → **integration** + Nock
- infra/* → en priorité unit, mais il est probable qu'on doive souvent en arriver à des tests d'integ

## Front/Integ VS. Front/acceptance VS. Cypress

TLDR : Components (integ) > acceptance > Cypress

**Components / intégration :**

- permet d’être exhaustif dans les comportements
- sont plus rapides
- permet de debugger facile

**Application / acceptance** :

- permet de débugger plus facile que Cypress (mais plus long que integ)
- permet de tester les routes (navigation, gestion du store), l’intégration des plugins

**Cypress :**

- objectif ultime : permettre de mettre en prod tous les jours de façon sécurisée
- plus proches de la réalité que les integ ou acceptance
- lourd à mettre en œuvre, long à exécuter

Perso, je blinde les tests de composants. Au moins 1 tests Cypress par fonctionnalité, pour tester les cas autouroutes ou les plus récurrents (dont gestion d'erreurs fréquentes). Les tests d'acceptance quand je suis coincé avec Ember, les routes, le store, obligé de me trimballer un dataset intermédiaire (plus gros qu'une propriété d'un test d'integ, mais pas aussi lourd que tout un compte & profil de compétence tel que dans Cypress).

**Comment by ajoanny** [comment]
## Front / apps Ember

### Actions

@jbuget pour ce qui est des actions il y en a beaucoup et je ne sais pas trop si avoir en grande partie des tests d'acceptance pour les tester c'est une bonne idée. Quand les actions sont dans un composant pourquoi ne pas les tester dans les tests d'intégration du composant ? C'est le composant qui porte l'action est-ce que ce n'est pas une raison suffisante pour tester les actions dans les tests du composant ?

### Templates

Pour tester les templates dans l'équipe prescription on essaye de mettre en évidence le contenu du template et pas sa structure. 
Voila un petit exemple :
Dans nos deux cas on essaye de vérifier qu'il y a bien le bon nombre d'éléments dans la page

`assert.dom('.campaign-list .table tbody tr').exists({ count: 2 }); `
Ici on voit bien la structure du template (tbody tr). Si jamais la structure du template change le test change même si le contenu reste le même.
(orga/tests/integration/components/routes/authenticated/campaigns/list-items-test.js:15)

` assert.dom('[aria-label="Sujet"]').exists({ count: 2 });`
Dans ce cas on vérifie la même chose, mais on ne sait pas comment le template est organisé et on vérifie qu'on a bien deux éléments.
(orga/tests/integration/components/routes/authenticated/campaigns/details/analysis-tab-test.js:36)

Je trouve que c'est une meilleure manière de tester les templates et de s'éviter de modifier les tests dès qu'on change la structure du dom. (@frinyvonnick Je te laisse me corriger si je dit une bêtise). Je pense que de cette manière les tests de template serais plus robuste et auront plus de valeur.


## Back / app Hapi.js

### Contrôleurs / Use Cases

Je trouve qu'il y a peu de valeur à écrire des tests unitaires sur les contrôleurs. Ils ont assez peu de logique et font la liaison entre les use cases et les serializer (api/lib/application/campaigns/campaign-controller.js:91) et je ne pense pas que le contrôleur ne devrait pas faire plus que ça.

Dans ce cas les tests unitaires on utiliserait des stub et des mock et on va créer une forte adhérence avec l'implementation. Quand il y a peu de logique je pense que le test unitaire n'est pas très intéressant .

J'ai le même avis sur le use case il est censé avoir un rôle de "liaison" entre les couches de l'application et avoir peu de logique et donc je dirais qu'il faut aussi des test d'intégrations.

J'ai du mal à voit l'interêt des tests d'acceptance des contrôleur . Du coup j'ai envie de les supprimer . 

## Cypress

Les tests end to end sont plus dur à maintenir et à écrire , ils ont beaucoup plus de raison de casser. Je pense qu'avec des bon tests d'intégration et unitaire la suite de tests devrait déjà

> permettre de mettre en prod tous les jours de façon sécurisée
 
Non ?

Est-ce que un test end to end par feature c'est réellement souhaitable ? Pourquoi pas uniquement des tests end to end sur les trucs critiques ?

TLDR:

 ## Front / apps Ember
template → integration avec mettant en avant le contenu du template et pas la structure

## Back / app Hapi.js

application/controller → integration
usecase → integration

**Comment by MelanieMEB** [comment]
En premier lieu, pour le back et e2e : 

**Back / app Hapi.js**
application/route → acceptance, avec la connexion à la bdd
application/controller → unit / mais est-ce utile vu le passe-plat ? Ou alors de l'integration 
usecase → unit
domain/* → unit
infra/repo → integration
infra/serializer → unit
infra/data/airtable → integration
infra/* → unit, integration si besoin

Là où je me pose le plus de question c'est sur la couche application. J'ai envie de mettre des tests d'acceptance dessus, pour pouvoir tester tout le chemin. Le controller faisant passe-plat, les tests unitaire sont souvent très limité et en faite c'est déjà testé avec l'acceptance.

**E2E alias Cypress**
Pour moi, les tests E2E ne devrait vérifier que les "happy path", où tout se passe bien. L'idée derrière la mise en place des tests E2E est d'éviter aux PO des tests manuels très long. Pour décider de ce qui doit être en E2E ou non est : 
- Est-ce le cas d'utilisation simple ? Si oui OK
- Est-ce un cas d'utilisation qui sera testé à chaque MEP par les PO  ? Si oui je dirais OK, et les prévenir de ne pas re-testé à chaque fois.

**Comment by lisequesnel** [comment]
Unitaire : Tout peut se tester (front ou back) en unitaire, l'important c'est de tout stuber/mocker. Dans certains cas cela n'est pas pertinent, ex : un test unitaire de controller, qui ne fait qu'appeler le usecase et appeler le serializer ou bien un test unitaire de repository où il faudrait stuber la base de données.
On teste également en unitaire les cas d'erreurs qui sont levés au sein de la fonction que l'on teste.

Intégration : On teste l'intégration de 2 ou plusieurs entités ensemble. Cela peut-être intra-couche (application, domain) ou bien inter-couches (domain + infrastructure).
Exemple côté back : l'intégration d'une usecase avec son service ; l'intégration d'un controller, du seriliazer, et de sa route ; l'intégration d'un usecase, d'un modèle du domaine, et des repositories appelés.
Exemple côté front : test de composant
On peut également tester les cas d'erreurs pertinents à tester.

Acceptance :
Côté front : tout ce qui touche à du changement de page.
Côté back : 1 test par route.
On peut également tester les cas d'erreurs pertinents à tester.

End-2-end : On ne teste que les cas passants.


Autre petit détail : on ne teste pas ce qui est déjà testé dans une autre lib/un autre framework.

**Comment by HEYGUL** [comment]
Discussion très intéressante !
Merci de l'avoir lancée :-)

A titre perso, je suis gêné que l'on confonde l'outil et l'objectif (cypress vs end-to-end).
Mais je comprend que les deux termes désignent les même types de tests.

J'ajoute une typologie de tests : les tests de non régression visuelle.
Je suis convaincu que ce type de tests nous permettraient d'augmenter notre niveau de confiance lors de chaque mise en production.

J'ai initié ce type de tests en utilisant un module de cypress, et donc ces tests sont mixés avec les tests end-to-end.
Après usage et une réflexion sur la durée et la maintenabilité des tests end-to-end, je suis de moins en moins persuadé que les tests de non régression visuelle doivent être faits dans les tests end-to-end.
Proposition (discutable en dehors de cette issue) : faire des tests de non régression visuelle dans les tests d'acceptance et/ou intégration front, via par exemple [ember-visual-test](https://cropster.github.io/ember-visual-test/latest/docs).

**Comment by laura-bergoens** [comment]
Du coup comment on vote / délibère / élabore un standard de testing autour de cette issue ?

**Comment by frinyvonnick** [comment]
C'est mardi à 14h qu'aura lieu la restitution de cette issue @laura-bergoens si je dis pas de bêtises 😄

**Comment by ajoanny** [comment]
@MelanieMEB pour les tests back de application/controller  si on teste les routes  avec  un accès à la db je l'impression qu'on test en même temps le contrôleur qui utilise le serializer et le use-case donc pas forcément besoin de tester les contrôleurs ailleurs.

**Comment by ajoanny** [comment]
J'ai du mal avec la notion de tests d'acceptance qu'on a. Je vois pas trop la différence entre nos tests d'acceptances et nos tests d'intégrations. 

J'ai cette définition pour les tests d'acceptances :

> Les tests d’acceptance ou tests fonctionnels sont les tests qui permettent de valider l’application d’un point de vue utilisateur.

C'est une que je retrouve bien dans les tests E2E. Je vois bien le parcours d'un utilisateur en les lisants.

et pour les tests d'intégrations :

> C’est l’objectif des tests d’intégration de vérifier que le “câblage” est bien fait et que notre composant communique effectivement avec ses dépendances, ni plus ni moins. On ne testera pas différents cas métiers.

J'ai l'impression que nos tests d'acceptances sont en réalités plus ou moins des tests d'intégrations.

Est-ce que quelqu'un a "la définition' de PIX sur ces types de tests ?

**Comment by sroccaserra** [comment]
Effectivement, plein de choses intéressantes.

> Je trouve qu'il y a peu de valeur à écrire des tests unitaires sur les contrôleurs. Ils ont assez peu de logique et font la liaison entre les use cases et les serializer (api/lib/application/campaigns/campaign-controller.js:91) et je ne pense pas que le contrôleur ne devrait pas faire plus que ça.

Les rôles du contrôleur HTTP sont :
- transformer la requête HTTP en paramètres pour les usecases en déléguant parfois à un désérialiseur
- peut-être valider deux trois trucs, comme le type des inputs mais pas la logique métier ? pareil en déléguant parfois à un désérialiseur
- passer la main au usecase avec les bons arguments
- soit récupérer la réponse du usecase et la transformer en réponse HTTP en déléguant à un sérialiseur
- soit récupérer les erreurs métier et les interpréter en code de retour HTTP en déléguant au traducteur d'erreur

Si je comprends bien, ton point est que si les sérialiseurs, les usecases, les déserialiseurs et la traduction erreur métier -> erreur HTTP sont testés unitairement, on n'a pas besoin de tester le contrôleur unitairement car un seul test d'intégration ou d'acceptance mettant en jeu le contrôleur va valider les branchements, c'est bien ça ?

**Comment by sroccaserra** [comment]
> Unitaire : Tout peut se tester (front ou back) en unitaire, l'important c'est de tout stuber/mocker.

Pour moi l'important est de stuber / mocker toutes les collaborations inconfortables. Données random, dates, appels lents comme la base de donnée ou le réseau ou le système de fichier. Une fois que c'est fait, je m'autorise à décider au cas par cas pour stuber / mocker ou pas ce qui reste.

Et d'ailleurs j'utilise l'heuristique "stub queries, mock commands", qui ne connait pas ?

**Comment by sroccaserra** [comment]
> Acceptance
Côté back : 1 test par route.
On peut également tester les cas d'erreurs pertinents à tester.

Je propose qu'on teste les cas d'erreurs HTTP plutôt en unitaire pour éviter de multiplier les tests d'acceptances, car ces derniers sont lents et parfois compliqués à alimenter pour avoir le cas précis d'erreur qu'on souhaite.

Pour ça deux options :
- soit on s'assure que le usecase a été testé pour l'erreur métier correspondante d'une part et d'autre part que la conversion d'erreur métier -> HTTP donne bien le bon status HTTP
- soit faire un test unitaire de contrôleur en bouchonnant le usecase pour qu'il renvoie l'erreur métier correspondante (à challenger avec l'autre discussion sur l'utilité de tester les contrôleurs).

**Comment by ajoanny** [comment]
>Si je comprends bien, ton point est que si les sérialiseurs, les usecases, les déserialiseurs et la traduction erreur métier -> erreur HTTP sont testés unitairement, on n'a pas besoin de tester le contrôleur HTTP unitairement car un seul test d'intégration ou d'acceptance mettant en jeu le contrôleur va valider les branchements, c'est bien ça ?

Oui c'est ça  et moins de logique ils auront moins aura besoin de tests intégrations / acceptances sur ces éléments.

Oui pour les erreurs on configure leur gestion dans le server.js:32, tester que les erreurs sont gérés correctement dans les contrôleurs à chaque fois revient à tester cette config plusieurs fois je trouve.
Je peux vérifier que j'utilise bien mon handler une seule fois et par contre bien tester mon handler de manière unitaire

**Comment by ajoanny** [comment]
> soit faire un test unitaire de contrôleur en bouchonnant le usecase pour qu'il renvoie l'erreur métier correspondante (à challenger avec l'autre discussion sur l'utilité de tester les contrôleurs).

Je pense qu'on devrait complètement isoler ces tests,  je crois que tous les contrôleurs peuvent gérer toutes les erreurs grâce à la config dans le server.js.
Peu importe dans quel contrôleur l'erreur est levée,  elle est gérée grâce à cette config (J'en suis pas sûr c'est à vérifier). 
Si c'est  bien le cas on a pas besoin de lier les tests d'erreurs à un contrôleur particulier.
On pourrait avoir un dummy contrôleur qui n'existerait que dans les tests et dans ces tests on forcerait uniquement des levées d'erreurs.

**Comment by sroccaserra** [comment]
Note : un atelier a eu lieu ce jours (voir ci-dessous pour le compte-rendu), la discussion va continuer en zoomant sur les sujets relevés lors de cette issue.
- https://1024pix.atlassian.net/wiki/spaces/DEV/pages/1401487453/2020-04-28+Atelier+Testing+tat+de+l+art
