### ISSUE TITLE
Discussion : que met-on dans un "usecase" chez Pix ?

### ISSUE THREAD

**Issue by sroccaserra** [1024pix/pix#1329]
## Contexte

Dans l'API de Pix, il y a un répertoire `/api/lib/domain/usecases` qui contient tous les points d'entrée vers le métier. Toute requête arrivant dans l'API passe systématiquement le relais à une fonction qui se trouve dans ce répertoire `usecases` et que par extension on appelle un "usecase".

L'objet de cette issue est de discuter de, rappeler, et mettre à jour ce qu'est un "usecase" dans ce contexte Pix.

**Comment by MelanieMEB** [comment]
Pour moi : un usecase est un "cas d'utilisation", donc il doit répondre à un besoin utilisateur dans sa nomination. Pour cela, c'est lui qui contient le métier et l'intelligence de ce que je veux faire.
Usecase : get-campaign-result : En tant qu'utilisateur, je veux mes résultats de campagnes. 
C'est au usecase `get-campaign-result` de savoir comment répondre à la question de l'utilisateur, et donc d'avoir la connaissance métier lié à cela (récupéré le target profil, etc...)

**Comment by ajoanny** [comment]
Le use case est un cas un orchestrateur. Il fait la liaison entre le domaine et le reste. Il a peu de logique et se contente de déléguer au domain à l'infra, et tout ce qu'on veut les différentes responsabilités il ne fait pas lui-même et ne contient pas la logique metier mais il sait qui doit collaborer pour traiter le cas d'usage qu'il représente.

**Comment by lisequesnel** [comment]
Le cas où il y avait débat, c'est celui-ci : https://github.com/1024pix/pix/pull/1322/commits/ec89e0bb1adce697018bfbf68e7da53c58b31f61#diff-1a91b0b5424cfa183d10843d2e6c0b11R24.

Le `if` doit-il se trouver dans le usecase ? Si non, où ?

**Comment by MelanieMEB** [comment]
> Le cas où il y avait débat, c'est celui-ci : ec89e0b#diff-1a91b0b5424cfa183d10843d2e6c0b11R24.
> 
> Le if doit-il se trouver dans le usecase ? Si non, où ?
> 
Pour moi, dans l'état actuelle, je dirais oui.

Si je comprends bien la vision @ajoanny  : 
- En simplifiant le cas : La campaignParticipation pourrait avoir une methode `.canHaveAnalysis` qui pourrait être appelé dans le usecase. La logique métier (partagé ou non) serait dans l'objet du domain. Est-ce ça ? 

Pour la suite du usecase, la récupération des `competences, tubes, targetProfile, validatedKnowledgeElements` demande de se balader avec pas mal d'objets différents, est-ce que l'idée est de les passer ensuite à une méthode de l'objet `campaignParticipation` qui recalculerait ? 
Si c'est le cas, j'ai l'impression d'exploser la logique métier à pleins d'endroit et de perdre la vision d'ensemble.

**Comment by sroccaserra** [comment]
Je vois la question un peu comme @ajoanny, traditionnellement une couche usecase exprime les points d'entrée métier, en restant la plus fine possible. Pour ça elle délègue au maximum le travail à des objets métier qui collaborent entre eux.

Ça nous oblige à mieux définir nos objets métier, et à leur donner du comportement. Ce qui n'est pas toujours simple, et qui est un processus itératif permanent.

**Comment by sroccaserra** [comment]
> Le cas où il y avait débat, c'est celui-ci : ec89e0b#diff-1a91b0b5424cfa183d10843d2e6c0b11R24.
>
> Le if doit-il se trouver dans le usecase ? Si non, où ?

Intéressant et pas simple : j'aurais effectivement envie de déléguer le if à un objet, mais pour savoir lequel j'aurais aussi envie de déléguer tout le travail de récolte qu'il y a au dessous. Je n'ai pas de réponse rapide, je regarde un peu mieux pour voir.

**Comment by ajoanny** [comment]
Oui je pense que ça va dans un objet du domaine (Je ne sais pas encore quel objet par contre)

Le use-case à mécaniquement la responsabilité de faire la liaison entre les couches si on rajoute de la logique notre use-case on lui rajoute des responsabilités.
On découpe les responsabilités : on sépare la partie logique métier et la partie persistance.
Pourquoi les use-cases aurait plusieurs responsabilités ? 
C'est un indice qui me fait dire que notre utilisation du use-case n'est pas la bonne.

Ensuite, une classe, une méthode ou une fonction avec plusieurs responsabilités c'est plus complexe de la tester et de la maintenir. En regardant les tests des use-cases j'ai le sentiment que ce n'est pas pratique et simple de les tester et pour moi c'est un indicateur qu'il y a un problème.

> Pour la suite du usecase, la récupération des competences, tubes, targetProfile, validatedKnowledgeElements demande de se balader avec pas mal d'objets différents, est-ce que l'idée est de les passer ensuite à une méthode de l'objet campaignParticipation qui recalculerait ?

Effectivement c'est un problème, mais je dirais que ça ne vient pas du use-case. Je pense que c'est lié à notre utilisation de la POO on passe tous les models directement aux fonctions / méthodes peut-être que ce n'est pas la bonne approche ?

Dans l'exemple de l'analyse des résultats de campagne on passe les tubes et les knowledge élements séparement pour ensuite grouper les knowledge elements par tube.
Est-ce qu'on peut récupérer des tubes qui portent directement les bons knowledge elements ?

Les repositories ne nous donnent pas toujours l'objet le plus pratique à utiliser. Peut-être que des use-cases différents ont besoin de représentations différentes d'un même model ? Dans ce use-case avoir les knowledge elements groupés par tube tout de suite c'est utile (et permettrait d'avoir moins de paramètres et de logique dans le model qui fait l'analyse), mais pas forcément pour les autres use-cases.
J'ai l'intuition que faire ce genre de choses dans les repositories c'est assez simple .C'est peut-être une piste ou pas en vrai j'en sais rien .

**Comment by sroccaserra** [comment]
> Peut-être que des use-cases différents ont besoin de représentations différentes d'un même model ?

Un peu comme discuté dans #649 et #1255 ?

> En ce sens, nous proposons de faire émerger une nouvelle typologie d'objets modèles du domaine : les Modèles de Lecture (ou Read Model objects).
>
> Par exemple, dans le cas des détails d'information d'identification d'un utilisateur, plutôt que récupérer et reconstruire tout un Utilisateur depuis la table `users` et ses tables relationnelles (`users_pix_roles`, `memberships`, `certification-centers-memberships`, etc.) en se contentant de reprendre la méthode existante `UserRepository#get(id)`, nous proposons de faire émerger une nouvelle méthode `UserRegpository#getForAdmin(id)` qui retourne non plus un `domain/models/User` mais un `domain/read-models/UserForAdmin`. Ainsi le repository continuerait de retourner un objet modèle du domaine, mais au moins il ne comporterait que les informations nécessaires au besoin / cas d'usage de récupérer les infos d'identité de l'utilisateur.

**Comment by ajoanny** [comment]
Exactement comme ça ! ;)

**Comment by sroccaserra** [comment]
Il y a aussi une discussion intéressante sur les `usecases` dans #1257 :

> Si le rôle du `usecase` n'est donc pas de tenir à jour un état, c'est à lui qu'incombe :
> - l'orchestration : c'est lui qui dicte l'ordre "chronologique" dans lequel exécuter différentes actions. C'est lui qui sait aiguiller sur tel ou tel chemin d'exécution et sait quoi faire quand certaines erreurs se produisent.
> - la récupération d'objets/données nécessaires à l'exécution par l'intermédiaire de `repository`

Si il y a l'aiguillage comme responsabilité du `usecase`, on peut bien imaginer que c'est lui qui fait le `if` 🤔

**Comment by ajoanny** [comment]
Pour le if je pense que c'est la responsabilité du model qui représente le recommandation d'un participant.

J'imagine ça comme ça :
- Les résultats sont partagés on fait le calcul de recommandation par tube
- Les résultats ne sont pas partagés on utilise des valeurs par défaut pour la recommendation de chaque tube. ('NA' comme dans l'export des résultats ?)

Ça me parait plus simple de le tester à cet endroit que dans le use case non ?

Je trouve plus propre que l'API renvoie une réponse disant que la recommendation n'est pas disponible plutôt que renvoyer null.

**Comment by ajoanny** [comment]
Et les lignes 35-36 ne sont pas utiles si le repository peut me donner seulement les tubes de la campagne que j'analyse

**Comment by sroccaserra** [comment]
Pour résumer ça donne quatre définitions assez proches dans les grandes lignes :

A)
> Un usecase est un "cas d'utilisation", donc il doit répondre à un besoin utilisateur dans sa nomination. Pour cela, c'est lui qui contient le métier et l'intelligence de ce que je veux faire.
Usecase : get-campaign-result : En tant qu'utilisateur, je veux mes résultats de campagnes.
C'est au usecase `get-campaign-result` de savoir comment répondre à la question de l'utilisateur, et donc d'avoir la connaissance métier lié à cela (récupéré le target profil, etc...)

B)
> Le use case est un cas un orchestrateur. Il fait la liaison entre le domaine et le reste. Il a peu de logique et se contente de déléguer au domain à l'infra, et tout ce qu'on veut les différentes responsabilités il ne fait pas lui-même et ne contient pas la logique metier mais il sait qui doit collaborer pour traiter le cas d'usage qu'il représente.

C)
> Une couche usecase exprime les points d'entrée métier, en restant la plus fine possible. Pour ça elle délègue au maximum le travail à des objets métier qui collaborent entre eux.

D)
> Si le rôle du `usecase` n'est donc pas de tenir à jour un état, c'est à lui qu'incombe :
> - l'orchestration : c'est lui qui dicte l'ordre "chronologique" dans lequel exécuter différentes actions. C'est lui qui sait aiguiller sur tel ou tel chemin d'exécution et sait quoi faire quand certaines erreurs se produisent.
> - la récupération d'objets/données nécessaires à l'exécution par l'intermédiaire de `repository`

Je pense que ces définitions sont bonnes, mais qu'elles ne sont pas suffisantes pour régler toutes les questions de conceptions qu'on trouve déjà dans les usecase Pix, je trouve intéressant de continuer à discuter sur la question de @lisequesnel.

**Comment by sroccaserra** [comment]
Sur la notion des `if` ou des embranchements de code dans les usecase Pix, dans mon compte je trouve environ 150 `if` ou `switch` dans 65 usecases. Comme il y a 110 usecases par déduction il y a 45 usecases qui ne contiennent ni `if` ni `switch`.
