### ISSUE TITLE
Test: Back - Controller - Comment les tester en TU/TI ?

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#1363]

**Comment by ajoanny** [comment]
J'ai globalement l'impression que les contrôleurs ressemble à ça et qu'il **doivent** ressembler à ça :

```javascript
  async getCollectiveResult(request) {
    const { userId } = request.auth.credentials;
    const campaignId = parseInt(request.params.id);

    const campaignCollectiveResult = await usecases.computeCampaignCollectiveResult({ userId, campaignId });
    return campaignCollectiveResultSerializer.serialize(campaignCollectiveResultSerializer);
  },
```

Le test unitaire ressemble à  : 
```javascript
  it('should return ok', async () => {
      // given
      usecases.computeCampaignCollectiveResult.resolves({});
      campaignCollectiveResultSerializer.serialize.withArgs({}).returns('ok');

      // when
      const response = await campaignController.getCollectiveResult({
        params: { id: campaignId },
        auth: {
          credentials: { userId }
        }
      });

      // then
      expect(response).to.be.equal('ok');
    });
```

Le test d'acceptance ressemble à  : 
```javascript
 it('should return campaign collective result with status code 200', async () => {
      // given
      const url = `/api/campaigns/${campaign.id}/collective-results`;
      const request = {
        method: 'GET',
        url,
        headers: { authorization: generateValidRequestAuthorizationHeader(userId) }
      };
      const expectedResult = {
        data: {
          type: 'campaign-collective-results',
          id: campaign.id.toString(),
          attributes: {},
          relationships: {
            'campaign-competence-collective-results': {
              data: [{
                id: `${campaign.id}_recCompetence1`,
                type: 'campaignCompetenceCollectiveResults'
              }]
            },
          },
        },
        included: [{
          id: `${campaign.id}_recCompetence1`,
          type: 'campaignCompetenceCollectiveResults',
          attributes: {
            'area-code': '1',
            'area-color': 'specialColor',
            'average-validated-skills': 1,
            'competence-id': 'recCompetence1',
            'competence-name': 'Fabriquer un meuble',
            'total-skills-count': 2,
          },
        }]
      };

      // when
      const response = await server.inject(request);

      // then
      expect(response.statusCode).to.equal(200, response.payload);
      expect(response.result).to.deep.equal(expectedResult);
    });
  });
```
Je suppose ça :

>  Les contrôleurs ont peu de logique métier et ne sont pas destinés à en avoir.

Si on doit le tester unitairement on doit vérifier qu'on appelle la fonction `computeCampaignCollectiveResult` avec les bons paramètres et on fait le même type de vérifications pour la méthode `campaignCollectiveResultSerializer.serialize`.

Dans ce cas le test unitaire vont mettre en évidence l'implémentation plus que le comportement. On crée de l'adhérence entre notre implémentation et notre test, si on change l'implémentation et qu'on garde le même comportement le test casse.
Le test passe si j'ai appelé la fonction `computeCampaignCollectiveResult` avec le paramètre.

Quand je vérifie uniquement que j'ai appelé correctement appelé la bonne fonction du bon use case  je vérifie en réalité l'intégration du contrôleur avec le use-case et le serializer. 
Le test unitaire ne garantit pas que le code fonctionne et je pense que ça lui donne moins d'intérêt. Si je casse le use-case ou le serializer le test passera toujours.

Si je fais un test d'intégration je vérifie (de manière non exhaustive) que le contrôleur à le bon comportement. Le contrôleur doit d'appeler le use-case et le serializer correctement pour que le test passe. Cette fois si je casse le use-case ou le serializer le test sera rouge. Quand le test est vert je sais que mon code fonctionne parce qu'il a bien traversé le use case, le serializer, etc. Le test a plus de raisons de casser, mais ce sont de bonnes raisons de casser : L'intégration avec le use-case / sérializer ne marche pas.
 
Je trouve plus utile et facile de faire uniquement des tests d'intégrations sur les contrôleurs.
Je pense que c'est faisable dans le cas où on se force à ne pas mettre de logique métier dans les contrôleurs et pour l'instant c'est pas toujours le cas.
Dans ce cas api/lib/application/assessments/assessment-controller.js:109 on a de la logique dans le contrôleur. Ici, le test unitaire me paraît utile, **mais** je pense que c'est pas une bonne idée / pratique de mettre cette logique dans les contrôleurs
