### ISSUE TITLE
Procédure de connexion

### ISSUE THREAD

**Issue by profelec** [1024pix/pix#1422]
Bonjour à tous,

Je suis enseignant et j’aimerais pouvoir me connecter à pix orga avec mon compte à l’aide d’un script php, afin de pouvoir récupérer les résultats de mes élèves au format csv des différentes campagnes que j’ai créé.

J’ai un peu de mal avec la procédure de connexion, est ce que quelqu’un pourrait me l’expliquer dans les grandes lignes ?

Merci d’avance,
ProfElec

**Comment by francois2metz** [comment]
@profelec Bonjour. 
Désolé de revenir vers vous si tard, est ce que cette demande est toujours d'actualité ?

**Comment by profelec** [comment]
Bonjour,

Merci pour votre retour, oui cette demande est toujours d’actualité.

Cordialement,
Yoann VARENNE

**Comment by profelec** [comment]
Bonjour,

Merci pour votre retour, oui cette demande est toujours d’actualité.

Cordialement,
Yoann VARENNE

**Comment by francois2metz** [comment]
@profelec Voici ce qu'il faut faire:

> POST https://orga.pix.fr/api/token

Les données a envoyer en form `application/x-www-form-urlencoded`:

> grant_type=password&username=VOTRE_EMAIL&password=VOTRE_MOTDEPASSE&scope=pix-orga

Vous récupérez un JSON qui est un objet similaire a cela:

```
{
  "grant_type": "bearer",
  "access_token": "LETOKEN",
  "user_id": votreuserid
} 
```

Ensuite vous pouvez utiliser le token dans les appels API suivant en mettant un header 

> Authorization: Bearer LETOKEN

:warning: Attention cette API n'est pas officiellement exposé et elle peut changer à tout moment.

Dites moi si cela vous convient.

**Comment by profelec** [comment]
Merci beaucoup !!!!!
