### ISSUE TITLE
Supprimer les gradients inutiles

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#1425]
Supprimer les gradients:
    $pix-blue-gradient
    $pix-pink-gradient
    $pix-purple-gradient
    $pix-orange-gradient

**Comment by francois2metz** [comment]
Je suis sur une branche https://github.com/1024pix/pix/tree/tech-remove-gradients ou j'enlève quasiment tout les gradient. Est-ce que tu pense qu'il faut en garder même des non utilisé ?
