### ISSUE TITLE
[Feature] Permettre aux utilisateurs de changer leur prénom/nom

### ISSUE THREAD

**Issue by vanilla-extracts** [1024pix/pix#1642]
Actuellement il est impossible de changer son prénom ou son nom sur la plateforme ( ou du moins c'est *bien caché* ), la plateforme s'adressant *principalement* aux élèves du secondaire et aux étudiant.e.s, il est à mon sens, logique qu'elle en suive les guidelines du gouvernement sur l'usage des prénoms d'usage afin de permettre à tous les étudiant.e.s transgenre d'utiliser leur prénom d'usage sans avoir à récréer un compte, en effets les dites personnes peuvent avoir bien avancé leur profil.

Aussi, il peut y avoir des changements d'état civil au niveau des prénoms ( pour les raisons indiquées au dessus ou autre ) ou de nom de famille ( pour diverses raisons ) et là aussi les utilisateurs.trices concerné.e.s n'ont peut être pas envie de tout recommencer à 0 pour ça. 

Pour toute ces raisons il est - en mon sens - logique que vous ajoutiez une possibilité de changer son prénom, je pense que beaucoup de personnes en bénéficierais. 
Merci,
Charlotte Thomas.

**Comment by HEYGUL** [comment]
Bonjour @coco33920,

Tout d'abord, au nom de toute l'équipe Pix, je vous remercie pour l'intérêt que vous portez à Pix.

Votre requête est légitime et nous vous remercions de l'avoir portée à notre attention.

Sachez qu'il est déjà possible de changer son nom et/ou prénom par simple demande au support utilisateur.
La fonctionnalité de changement de nom et/ou prénom (pour quelle que raison que ce soit) est déjà inclue dans la roadmap de développement de notre produit.
Nous ne pouvons vous donner une date de mise à disposition pour le moment.
Nous ne manquerons pas de communiquer à propos de l'avancement de cette fonctionnalité.

Très bonne journée à vous.
Guillaume Lagorce pour Pix

**Comment by vanilla-extracts** [comment]
D'accord merci pour ça, à vrai dire j'hésitais à envoyer un mail au support utilisateur d'abord.
Merci pour l'indication que c'est sur la roadmap c'est super :)!
Je vous souhaite alors un bon courage et suivrais votre avancée avec plaisir
Merci,
Charlotte Thomas
