### ISSUE TITLE
Petite erreur sur README.md

### ISSUE THREAD

**Issue by ThierryNapspirit** [1024pix/pix#196]
A la ligne: 

1/ Récupérer le code source
$ git clone git@github.com:1024pix/pix.git && cd pix

C'est "git@github.com/1024pix/pix.git && cd pix" 
=> "/1024" au lieu de ":1024" dans le lien

En tout cas bravo pour le projet.
Thierry.

**Comment by jonathanperret** [comment]
Bonjour Thierry,

L'instruction donnée dans le`README.md` (`git clone git@github.com:1024pix/pix.git`) fonctionne pour moi. Quelle erreur rencontrez-vous ?
