### ISSUE TITLE
Menu déroulant "Enseignement" : flèche non interactive

### ISSUE THREAD

**Issue by DegrangeM** [1024pix/pix#1972]
![image](https://user-images.githubusercontent.com/53106394/95257534-beed4e00-0824-11eb-9d5f-37537aa18ff7.png)

Pour ouvrir le menu déroulant "Enseignement", cliquer sur la flèche vers le bas ne fonctionne pas, il faut absolument cliquer sur le texte. C'est contre intuitif.

**Comment by celineung** [comment]
Bonjour @DegrangeM ,

Merci de nous avoir remonté ce problème.
Nous l'avons pris en compte et le correctif sera bientôt visible sur le site.

Très bonne journée à vous.

Céline Ung, de Pix
