### ISSUE TITLE
[BUG] Sur les environnement hors production, la déconnexion renvoie sur les environnements de production

### ISSUE THREAD

**Issue by chrc** [1024pix/pix#1995]
Sur les environnements Intégration et Recette, la déconnexion redirige vers l'environnement de production.
Cela peut mener des modifications de données involontaires, l'utilisateur pensant se reconnecter sur l'environnement d'origine

**Comment by francois2metz** [comment]
Je n'ai pas réussi a reproduire le problème sur mon pix en recette.
