### ISSUE TITLE
Inscription sur IE 11

### ISSUE THREAD

**Issue by lzbk** [1024pix/pix#201]
Bien que la configuration requise stipule [IE 9](https://pix.fr/aide/configuration-technique), il semblerait qu'il ne soit pas possible de se créer un compte sur Pix avec IE 11, le formulaire se répète à l'infini quand on répond au capcha (ou un peu avant) sans faire apparaitre le bouton envoyer.

2 de mes étudiantes sont restées coincées un moment avant que je leur fasse utiliser firefox.

**Comment by DaRiviere** [comment]
Bonjour, merci pour votre retour, nous analyserons ce bug au plus vite.
En attendant n'hésitez pas à conseiller à vos élèves d'utiliser un autre navigateur que IE 11 pour se créer un compte Pix.
