### ISSUE TITLE
Retour sur les résultats

### ISSUE THREAD

**Issue by lzbk** [1024pix/pix#202]
Tel que pix est fait quand on termine un test on a un bilan avec des recommandations de ressources pour approfondir tel ou tel point. Cependant une fois qu'on est retourné à son profil, on ne peut plus y accéder, ce qui est un peu dommage…

Ce serait bien de pouvoir recliquer sur le test de la compétence pour en revoir les erreurs et réussites.

**Comment by DaRiviere** [comment]
Bonjour, vous adressez ici un besoin dont nous avons connaissance.
Cette fonctionnalité n'a pas encore été développée, mais devrais l'être sous peu.
