### ISSUE TITLE
Barre de progression

### ISSUE THREAD

**Issue by lzbk** [1024pix/pix#203]
Plusieurs étudiants ont regretté de ne pas savoir où ils en étaient du test…

J'imagine que le système ajoute parfois des questions en fonction des réponses faites. Peut-être serait-il toutefois possible de compter le nombre de questions maximum possible à partir d'un embranchement et de faire la progression par rapport à cette métrique. 

Quoi qu'il en soit un indicateur, même un peu imprécis du nombre de questions restant serait appréciable.

**Comment by DaRiviere** [comment]
Bonjour, en effet la durer du test varie en fonction des réponses données.
Nous travaillons actuellement sur une nouvelle modalité d'évaluation qui embarquera une barre de progression.

N'hésitez pas à revenir régulièrement sur Pix pour suivre les avancées du projet, merci de votre retour !
