### ISSUE TITLE
[BSR] La version de Cypress utilisée n'est pas à jour

### ISSUE THREAD

**Issue by chrc** [1024pix/pix#2374]
Cf: [Changelog](https://docs.cypress.io/guides/references/changelog.html#6-0-0) de Novembre 2020

## Premières étapes
* cypress 5.3.0 => 5.6.0
* cypress-visual-regression 1.3.1 => v1.5.3 (Bumps to Cypress v5.6.0)
* cypress-cucumber-preprocessor 2.5.0 => 4.0.0

**Comment by VincentHardouin** [comment]
Réalisé dans la PR https://github.com/1024pix/pix/pull/2627
