### ISSUE TITLE
[TECH] Les types utilisés dans les clefs étrangères ne sont pas homogènes.

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#2467]
Il ya quelques BIGINT qui sont utilisés sur la BDD API au lieu de INTEGER sans raison valable
- soit la colonne contient uen référénce vers un autre colonne de type INTEGER
- soir la volumétrie ne justifie pas la pénalité de performance de BIG INTEGER

```
tutorial-evaluations.userId
user-orga-settings.currentOrganizationId
user-orga-settings.userId
user_tutorials.userId
```

**Comment by yaf** [comment]
Est-ce que cette PR est toujours d'actualité ?

C'est une tentative de « PDD » (Pull request Driven Development) ?

**Comment by octo-topi** [comment]
Cette issue est toujours d'actualité

**Comment by francois2metz** [comment]
C'est vrai. La pénibilité de changer cela dépasse la pénalité de performance potentielle. On ferme.
