### ISSUE TITLE
Erreur challenges

### ISSUE THREAD

**Issue by Bouh** [1024pix/pix#2497]
Bonjour

Je suis utilisateur de la platforme et je suis sur une epreuve dont la solution est nul part, et encore moins dans le code source.

https://epreuves.pix.fr/perso3.html

![image](https://user-images.githubusercontent.com/1670670/106770570-685f1780-663e-11eb-8dd7-a8794dcb37cd.png)

Je ne pense pas être au bon endroit pour rapporté cette erreur, de toute manière j'ai fait un rapport en utilisant le bouton **Signaler un problème** en dessous de la question.

Malheuresement la réponse étant indisponible mon résultat a cette réponse sera mauvaise, se qui fausse les tests.

**Comment by Bouh** [comment]
Je n'ai aucun bloqueur ou extension qui pourait interféré avec.

![image](https://user-images.githubusercontent.com/1670670/106771092-e6232300-663e-11eb-99dc-0258b8370f89.png)

**Comment by Bouh** [comment]
L'énoncé

![image](https://user-images.githubusercontent.com/1670670/106771328-21255680-663f-11eb-887d-2296bcfab910.png)

**Comment by MelanieMEB** [comment]
Bonjour,

Après vérification, ces épreuves n’ont pas de problème et fonctionnent bien. Le lien pour accéder au réseau social proposé dans l’épreuve est correct.

Cette épreuve ne demande pas d’aller dans le code source pour trouver la réponse, elle vous donne d’autres informations pour y répondre.

Bonne journée.

**Comment by Bouh** [comment]
>Après vérification, ces épreuves n’ont pas de problème et fonctionnent bien. Le lien pour accéder au réseau social proposé dans l’épreuve est correct.

Il est bon de le savoir merci.
Néanmoins avec avoir utilisé les identifiants de Julia, une fois sur son profil personne ne souhaite devenir son ami, ce qui est tout l'objectif de la question.

Je vous remet ici une image de l'espace personnel de Julia qui indique qu'une partie de ce que la page devrait.
![image](https://user-images.githubusercontent.com/1670670/106779504-5766d400-6647-11eb-9d1e-5276e6f1aceb.png)

Vous voyez bien qu'il manque le nom de l'ami en question en début de phrase.

>Cette épreuve ne demande pas d’aller dans le code source pour trouver la réponse, elle vous donne d’autres informations pour y répondre.

Je le sais bien et en dépit d'avoir la réponse dans la page comme il devrait être le cas j'ai été cherché la réponse dans le code source et la fonction qui décode le nom de l'ami en question est non fonctionnel, le résultat reste une chaine de caractère vide.

**Comment by Bouh** [comment]
Ma solution pour trouvé la réponse aura été de prendre le contenu de getWord défini en ligne 15.
Gardé uniquement les chiffres car vous semblez itéré dessus tout les trois caractères. Donc (079,108,105,118,105,101,114)
Et utilisé fromCharCode comme vous semblez le faire.

`String.fromCharCode(079,108,105,118,105,101,114)`

 Pour finalement avoir le prénom, qui je reconfirme après vérification n'est nul part même en ayant réussi l'épreuve sans ouvrir le code source.


<details>


```
String.fromCharCode(079,108,105,118,105,101,114)
```

Donne `Olivier`


![image](https://user-images.githubusercontent.com/1670670/106783173-4750f380-664b-11eb-8cfc-d6f7f9c5dcc3.png)
</details>

**Comment by MelanieMEB** [comment]
Votre problème de prénom vide est normal lorsque vous utilisez le lien du HTML que vous nous avez fourni dans votre premier message. Nous avons fait une vérification et toutes les épreuves sont fonctionnelles, merci pour votre message.

Nous fermons votre issue car elle contient des informations sur les épreuves Pix et sur leurs réponses.

**Comment by jonathanperret** [comment]
@Bouh J'ajoute des félicitations pour votre détermination à chercher la réponse dans le code source. Si elle n'y figure pas sachez que c'est délibéré pour éviter justement qu'il soit trop facile de "contourner" l'épreuve.

Si néanmoins vous découvriez des failles dans la sécurité des épreuves et que vous souhaitiez nous en informer de manière responsable je vous invite à utiliser la page https://support.pix.fr/fr/support/tickets/new plutôt qu'une _issue_ GitHub.
