### ISSUE TITLE
[TECH] La route  API /users/{id}/memberships n'est plus utilisée

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#2509]
**Constat**
Périmètre équivalent repris par les routes
- `/api/memberships/{id}` pour les memberships d'une organisation
- `/api/prescription/prescribers/` pour les memberships d'un utilisateur

Plus de référence explicite dans les Front
Pas d'appel depuis 15 jours en production

**Solution**
Supprimer la route

**Comment by francois2metz** [comment]
https://github.com/1024pix/pix/pull/5166
