### ISSUE TITLE
[TECH] Les tests Cypress ne peuvent pas être exécutés isolément

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#2524]
## :unicorn: Problème
Lorsqu'un nouvel utilisateur lance les tests E2E pour vérifier qu'ils s'exécutent correctement, l'affichage est monopolisé par Cypress (des navigateurs apparaissent et disparaissent).

Lorsqu'un utilisateur habituel exécute les tests E2E sur une application pour s'assurer de la non-régression, le même scénario se produit.

## :robot: Solution
Fournir des scénarios de test pour chaque Front, exécutable en ligne de commande (headless)

**Comment by francois2metz** [comment]
On a un  `scripts/tests-e2e` qui permet de lancer le tout d'une manière isolé avec ou sans navigateur.
