### ISSUE TITLE
Export participants PixOrga - Ordre non garanti

### ISSUE THREAD

**Issue by nicolasunivlr** [1024pix/pix#2675]
En faisant un export de pix orga plusieurs fois de suite, la liste des participants n'est jamais dans le même ordre.
Cela est très génant si on veut faire des statistiques au fur et à mesure des arrivées du parcours.
L'année dernière, j'avais juste à reprendre les dernières lignes du fichier pour compléter mes stats. Là je suis obligé de tout reprendre...

**Comment by HEYGUL** [comment]
Bonjour @nicolasunivlr 

Merci beaucoup pour votre intérêt pour Pix.
Nous allons regarder ce soucis d'export non trié.
Si j'ai bien compris, il serait plus simple d'usage que les lignes du fichier CSV soient triées par ordre de date de partage des résultats. Pouvez-vous me confirmer ce point ?

Très bonne journée à vous,

GUL pour Pix

**Comment by nicolasunivlr** [comment]
Merci @HEYGUL,
Le tri par ordre croissant de partage serait une bonne option, on aurait juste à prendre les derniers éléments du fichier si on fait plusieurs export du même parcours.
Bonne journée.

**Comment by lisequesnel** [comment]
Bonjour @nicolasunivlr,

Pour vous éviter de tout reprendre, et en attendant que nous développions une solution, vous pouvez de votre côté trier sur la colonne de votre choix (date de partage ou date de début du parcours) sur le fichier téléchargé à l'aide d'un outil de tableur.
Bonne journée.

Lise pour Pix

**Comment by nicolasunivlr** [comment]
Bonjour @lisequesnel ,
Ce n'est pas un problème technique pour moi. Je gère les tris, les sélections multiples, les filtres, ...
Cependant, l'année dernière, je n'avais pas ce comportement et plus on manipule un fichier, plus on risque de faire une erreur humaine.
Bonne journée.
