### ISSUE TITLE
Accès au Pix Editor

### ISSUE THREAD

**Issue by demangejeremy** [1024pix/pix#2698]
Bonjour la team :wave: 

Je souhaite mettre Pix en local. Tout est bon au niveau de l'installation, seulement, je n'arrive pas accéder au dépôt du LCMS qui remplace le Airtable (Pix Editor) : https://github.com/1024pix/pix-editor :sob: Car je voudrais ajouter mes propres questions.

Possible de le mettre en Open Source ou me donner un accès au dépôt ? J'en ferai bonne usage et pourrai également y contribuer :smile: 

Y a-t-il une alternative sinon ?

Merci beaucoup, par avance, pour votre retour :+1:

**Comment by francois2metz** [comment]
Bonjour Jérémy,

Merci de ton intérêt pour PIX et pix-editor. Nous avons un plan de prévu pour ouvrir pix-editor et son API (et sortir d'airtable). 
On va en discuter de l'équipe si on peut accélérer l'ouverture ou te donner un accès.

On aimerait beaucoup en savoir plus sur ton projet dans tout les cas !

**Comment by demangejeremy** [comment]
Bonjour @francois2metz :handshake: 

J'aimerais construire une alternative française à freeCodeCamp (https://github.com/freeCodeCamp/freeCodeCamp), sur des sujets de machine learning et de data-visualisations, avec de l'interactivité et une meilleure interface (celle de Pix !!). J'ai scrappé les questions en anglais de ce projet Open Source et commence la traduction, tout en modifiant certaines questions pour utiliser les dernières bonnes pratiques connues dans ce domaine. 

Pour cette raison, j'espère vraiment avoir le plus tôt possible avoir accès au Pix Editor (pour concrétiser ce projet et le tester au plus vite). J'ai déjà modifié l'interface aux couleurs de mon projet (je pourrai vous montrer ce que cela donne). Et bien évidemment, au plaisir d'échanger avec vous et de contribuer à certaines parties de Pix une fois toutes les cartes en main ! ;-)

A très vite et merci !

**Comment by francois2metz** [comment]
Bonjour Jérémy,

Merci pour ces détails !

Après discussion on est un peu embêté car on ne peut pas ouvrir le code source de pix-editor sans un audit.

On est conscient que les changements d'archi récents font que le monorepo de Pix n'est plus autonome et nous travaillons la dessus. Sortir d'airtable et libérer tout cela va prendre encore du temps (probablement plusieurs mois). On ne peut pas prendre d'engagements de délai pour le moment.
On espère tous que cela va se régler le plus rapidement possible.

**Comment by demangejeremy** [comment]
Merci François pour ton super retour et les détails apportés 😃 

Est-ce possible en attendant d'avoir accès au tags de la dernière version avec Airtable ou un modèle du Airtable qui va avec pour commencer le développement de mon côté ? (ce serait vraiment génial !)

Impatient d'utiliser le code Pix et que ce projet sur les sujets de dataviz voit le jour !

Un grand merci de prendre le temps de répondre à mes différentes question.

**Comment by francois2metz** [comment]
La dernière version sans LCMS: https://github.com/1024pix/pix/releases/tag/v2.243.0

Je peux te partager la base "Pix - Minimal" sur airtable qui est utilisé lorsqu'on clone le dépot Pix par défaut. Donne un email pour cela et je te la transfère.

**Comment by demangejeremy** [comment]
Merci beaucoup.
Et voici pour recevoir le clone : ***@***.***

**Comment by francois2metz** [comment]
@demangejeremy L'adresse email a été mangé par github ;)

**Comment by demangejeremy** [comment]
Aïe... Je viens de vous envoyer un petit mail pour vous donner mon email exact ;)

**Comment by francois2metz** [comment]
Le transfert a été fait avec le compte oss airtable avec une base nommée clairement. 

Il me semble que le boulot est fait pour cet issue.

**Comment by demangejeremy** [comment]
Hello la team Pix 👋 

Encore un grand merci à @francois2metz pour le partage du Airtable !

Je me permets de ré-ouvrir cette issue car une plateforme de test de Pix que j'avais mis sur un de mes serveurs (avec la version v2.243.0) a été compromise. Cela est je pense dû à différentes librairies qui ne peuvent être fixé sans modifier le code. Je pense que cela a été fixé depuis, mais sur la nouvelle version avec le Pix Editor.

Auriez-vous une date de publication du Pix Editor ? Y a-t-il moyen de sécuriser correctement une instance avec la version v2.243.0 ?

Je travaille en parallèle en tant qu'ingénieur d'études dans un laboratoire de recherche et j'ai pu convaincre d'utiliser Pix pour y faire un quiz ludique sur les élections régionales (qui sortira dans deux semaines). Si vous avez des best practices au niveau du déploiement, je serai très heureux de discuter avec vous et de vous en dire plus sur le projet :)

Merci par avance de votre aide

**Comment by francois2metz** [comment]
Bonjour Jérémy,

Je suis bien désolé de savoir qu'il y a un problème pour déployer la version 2.243.0. Malheureusement, si nous ne ménageons pas nos efforts actuellement pour sortir d'airtable, refactorer du code et une foultitude d'autres activités passionnantes, nous ne sommes clairement pas prêt pour ouvrir Pix-editor. 
Peut tu nous en dire plus sur le problème que tu a rencontré pour déployer Pix ?

Je te propose qu'on se contacte par email et qu'on s'appelle pour discuter de tout ça.

François

**Comment by francois2metz** [comment]
Ton souhait a été exaucé et le code source de Pix-editor est désormais en ligne: https://github.com/1024pix/pix-editor/.

**Comment by LorisOclock** [comment]
Bonjour la Pix team 😄

Est-il possible d'avoir la base Airtable pour pouvoir utiliser Pix Editor ?

Merci par avance !

**Comment by francois2metz** [comment]
Bonjour @LorisOclock, peux tu envoyer un mail a francois.de-metz[at]pix.fr en indiquant l'email du compte airtable utilisé. Cela me permettra de transférer la base minimale.

**Comment by gimas-cned** [comment]
Bonjour l'équipe Pix,

Serait-il possible d'avoir accès à la base Airtable pour tester Pix Editor ?

Merci et bonne journée
