### ISSUE TITLE
Authentification superflue pour le rechargement de cache planifié

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#2747]
# Problème
Le rechargement de cache planifié (conteneur scalingo `background`) effectue le rechargement par appel API sur une route authentifiée` api/scripts/reload-cache-everyday.js`, ce qui entraîne le stockage d'un compte dans les variables d'environnement.
```
PIXMASTER_EMAIL=
PIXMASTER_PASSWORD=
```
# Solution
Or, comme l'exécution se fait sur un périmètre sécurisé (API elle-même), la méthode peut être invoquée sans authentification
`CacheController.refreshCacheEntries`

# Note
Le contenu de `CacheController.refreshCacheEntries` peut être déplacé dans un use-case, voir [ADR](https://github.com/1024pix/pix/blob/dev/docs/adr/0020-caractere-obligatoire-use-case.md)

D'autres scripts utilisent aussi ce mécanisme:
- create-or-update-sco-organizations.js
- update-sco-organizations-with-is-managing-students-to-true.js
- api/scripts/update-sco-organizations-with-province-code-and-external-id.js

**Comment by HEYGUL** [comment]
Une solution peut être d'utiliser Bull comme la création de release planifiée sur lcms. cf https://github.com/1024pix/pix-editor/pull/111

**Comment by francois2metz** [comment]
Fixed in https://github.com/1024pix/pix/pull/4010
