### ISSUE TITLE
Utiliser une convention de nommage dans les scripts SQL du référentiel

### ISSUE THREAD

**Issue by AbcSxyZ** [1024pix/pix#2803]
Sur l'exercice de la section "Programmer", l'exercice avec les consignes suivantes : 
```
Voici une base de données présentant la programmation d'un théatre.

Elle comporte 4 tables : PIECE, SEANCE, CATEGORIE, TARIF.

Combien de pièces de Danse ou de Musique sont proposées pour un tarif réduit strictement inférieur à 15 euros ?
```
Utilisant le fichier `THEATRE_PIX.sql`
Les noms de colonnes n'ont aucun standard : du upper et lower camel case, du snake case, du camel case fini en majuscule,  un accent, parfois une majuscule au début, parfois non...
Un bon mix de toute ce qui peux exister, et quelques inventions ? J'ignore si c'est volontaire (je n’espère pas) mais je trouve ça étonnant.

Liste des tables, avec leurs colonnes :
```
PIECE
idPIE | Titre | Auteur | IdCat | codeTarif
SEANCE
idSEA | idPIE | date | heure
CATEGORIE
idCAT | Nom
TARIF
codeTarif | tarif_réduit | plein_tarif
```

J'ignore si le problème s'applique à d'autres fichiers sql, pas fait attention sur les précédents.
Uniformisez et se tenir à un type de case me paraît utile pour limiter les confusions.

**Comment by ftort** [comment]
Oui vous avez parfaitement raison. Je vais corriger cela. 
Si vous avez une convention à me recommander qui serait parlante au plus grand nombre, n'hésitez pas.
En tout cas merci pour ce signalement.

**Comment by AbcSxyZ** [comment]
J'ai regardé s’il y avait une convention de nommage pour sql, pas forcément l'air.
Soyez surtout consistant, au sein d'un même exercice voir entre tous les exercices.

Proposition : la même convention que le code du site, lower camel case (?).

**Comment by octo-topi** [comment]
Ce n'est pas complémteent lié, car cet outil linte les schémas de BDD instanciés, pas le code source
Mais je le mentionne quand même https://github.com/kristiandupont/schemalint

Exemple d'utilisation
https://github.com/1024pix/pix/pull/3804
