### ISSUE TITLE
Help with local installation - no access to plateform

### ISSUE THREAD

**Issue by nfavrod** [1024pix/pix#299]
Hello,

I'm trying for a few week to install pix locally, and managed to run it on my laptop.

But after seeding the DB - I always have the following error 

`
181129/212609.337, [response] http://retina-nico.local:3000: options /api/authentications {} 200 (15ms)

181129/212609.356, [response,api] http://retina-nico.local:3000: post /api/authentications {} 400 (54ms)

181129/212613.567, [response,api] http://retina-nico.local:3000: post /api/authentications {} 400 (13ms)
` 

(Full log attached)

Can someone please help me? 

Thanks

[log pix retina-nio.txt](https://github.com/1024pix/pix/files/2664855/log.pix.retina-nio.txt)

**Comment by jonathanperret** [comment]
Bonjour, avec quel compte utilisateur essayez-vous de vous connecter ?

**Comment by nfavrod** [comment]
Avec ceux qui sont : https://github.com/1024pix/pix/blob/dev/api/db/seeds/data/1st-to-create/users.js
ou plus loin dans les scripts... 

J'ai une nouvelle erreur quand je vais sur récupérer un mot de passe 

```
{"name":"pix-api","hostname":"retina-nico.local","pid":14576,"level":50,"err":{"message":"secretOrPrivateKey must have a value","name":"Error","stack":"Error: secretOrPrivateKey must have a value\n    at Object.module.exports [as sign] (/Users/nico/Devel/pix/pix/api/node_modules/jsonwebtoken/sign.js:70:20)\n    at Child.generateTemporaryKey (/Users/nico/Devel/pix/pix/api/lib/domain/services/reset-password-service.js:9:25)\n    at bound (domain.js:301:14)\n    at Child.runBound (domain.js:314:12)\n    at Child.tryCatcher (/Users/nico/Devel/pix/pix/api/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/nico/Devel/pix/pix/api/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/Users/nico/Devel/pix/pix/api/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/Users/nico/Devel/pix/pix/api/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/Users/nico/Devel/pix/pix/api/node_modules/bluebird/js/release/promise.js:694:18)\n    at _drainQueueStep (/Users/nico/Devel/pix/pix/api/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/Users/nico/Devel/pix/pix/api/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/Users/nico/Devel/pix/pix/api/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/Users/nico/Devel/pix/pix/api/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)"},"msg":"secretOrPrivateKey must have a value","time":"2018-12-11T09:45:27.611Z","v":0}
```

**Comment by nfavrod** [comment]
? des nouvelles? Je ne comprend pas ce que je fais faux... J'ai suivi le README mais c'est écrit de vous contacter pour avoir un accès...

**Comment by nfavrod** [comment]
Bonjour,

y a-t-il un "sercet" a mettre dans le .env de l'API...

Ce serait sympa de m'aider svp :-)

Merci
Nicolas

**Comment by nfavrod** [comment]
Bonjour - des nouvelles?

**Comment by DaRiviere** [comment]
Bonjour,

Tout d'abord désolé pour le temps de réponse.

En effet il y a bien un secret d'authentification à ajouter dans un fichier `.env` dans le répertoire `api`, pour pouvoir se connecter.
Vous pouvez par exemple le renseigner comme : `AUTH_SECRET=toto`.

Après cela l'API va vous demander une clé d'authentification pour pouvoir vous connecter à notre référentiel de connaissance.

**Pour le moment nous ne pouvons pas vous la fournir.**

Si vous tenter de lancer l'application Pix dans le cadre d'une expérimentation professionnelle ou universitaire. Je vous invite à nous contacter par mail pour officialiser ce partenariat.
Si l'objectif est personnel, je vous invite à modifier l'API pour qu'elle requête la base de votre choix.

Merci pour l'intérêt que vous portez à Pix !

**Comment by nfavrod** [comment]
You make my day!!!!!
Merci beaucoup! 
Oui je vais tester tout ça et je vous tiendrais au courant de mes expérimentations.
Génial!

**Comment by jbuget** [comment]
Bonjour @nfavrod, comme convenu, nous avons travaillé ces dernières semaines pour rendre la plateforme plus ouverte, cf. #1172. A cette fin, nous avons créé une base d'épreuves de type bac-à-sable et fait en sorte que tout soit installable en 1 commande `npm run configure`. Vous pouvez à nouveau tenter d'installer Pix en local. ;-)
