### ISSUE TITLE
Compétence "Développer des documents textuels": problème fichier PowerPoint, mot caché sous l'étoile

### ISSUE THREAD

**Issue by fp37** [1024pix/pix#3114]
Bonjour,

Petit feedback sur la question _"Dans la présentation à télécharger, un mot est caché sous l'étoile. Trouvez-le!"_

Dans le fichier PPTX, il est impossible de modifier ou déplacer l'étoile dans la mise en forme du masque / arrière plan pour obtenir le mot caché. 

Problème non reproductible avec le fichier ODP.

**_Microsoft Powerpoint 2019 utilisé, problème identique sur Google Slides après importation du PPTX._**

Bonne réception, cdt.

![feedback_pix](https://user-images.githubusercontent.com/62597770/122356802-6fceef80-cf53-11eb-89d6-1ccab3781b00.PNG)

**Comment by bpetetot** [comment]
Merci beaucoup pour ce retour, nous allons regarder ce problème.

**Comment by francois2metz** [comment]
Corrigé.
