### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [1024pix/pix#3170]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by francois2metz** [comment]
Hi @huntr-helper. Sorry for the delay. We now have a SECURITY.md file on the repository: https://github.com/1024pix/pix/blob/dev/SECURITY.md
