### ISSUE TITLE
Bouton "J'ai un code" sur mobile

### ISSUE THREAD

**Issue by DegrangeM** [1024pix/pix#3207]
Sur téléphone, le bouton "J'ai un code" n'est pas toujours visible directement dans le menu,
Sur le téléphone d'une élève, il fallait scroller vers le bas pour le voir (il était entièrement invisible sinon) et ce n'était pas un problème de place puisqu'il y avait beaucoup d'espace libre au dessus. J'ai au début cru que le bouton n'était pas présent sur mobile.
Sur mon téléphone (Mi 9, navigateur Brave), le bouton est partiellement visible alors qu'il y a de la place également au dessus.

Capture d'écran de mon téléphone

![image](https://user-images.githubusercontent.com/53106394/99538497-565dc900-29ad-11eb-8092-e5b303e3ca48.png)

**Comment by francois2metz** [comment]
Le menu a été retravaillé depuis l'ouverture de ce problème. Il n'y a plus d'espace vertical entre les entrées du menu et le bouton "J'ai un code".
