### ISSUE TITLE
Code parcours sur 2 lignes

### ISSUE THREAD

**Issue by bristow** [1024pix/pix#3223]
Bonjour,

Sur certaines créations de parcours, le code passe sur 2 lignes dans l'interface (cf ci-dessous), on peut donc facilement donner un mauvais code, est-il possible de modifier cela ?

![Sélection_701](https://user-images.githubusercontent.com/1156507/97737767-bf080300-1add-11eb-8903-da50cb94aa3b.png)

Merci

**Comment by francois2metz** [comment]
@bristow Bonjour. Nous n'avons pas réussi à le reproduire. Il y a eu des changements récemment, nous avons peut être corrigé le problème suite à cela. Pouvez vous réessayer et si vous arrivez a le reproduire, nous communiquer plus d'informations (résolution et navigateur) ?

**Comment by bristow** [comment]
En fait, cela va dépendre de la résolution de l'ordinateur. Mais visiblement, c'est moins flagrant qu'avant car vous avez baissé la taille des caractères et mis un bouton _copier_.
En outre, sur l'interface smartphone, on a enfin quelque chose d'utilisable :tada: 

Je clos donc la demande et je suis enfin content que vous preniez en compte les remontées via cette plateforme !

**Comment by francois2metz** [comment]
Désolé du temps de réaction effectivement. L'issue avait été posté initialement sur 1024pix/pix-site ce qui n'a pas aidé au tri.
