### ISSUE TITLE
[Bug Visuel] méthode de connexion vide quand connexion avec un ENT

### ISSUE THREAD

**Issue by WeeskyBDW** [1024pix/pix#3529]
## Description
quand on est connecté à Pix, via un ENT, nous avons rien dans "mes méthodes de connexions" (<https://app.pix.fr/mon-compte/methodes-de-connexion>)

## Résultat attendu
qu'il m'affiche qu'une de mes méthodes soit "Connexion via un ENT"

## Résultat obtenu
un rectangle blanc sans rien dedans

## Comment reproduire
- connecter vous à un environnement de travail numérique (ENT), par exemple <https://www.ent.auvergnerhonealpes.fr/>
- aller dans "Ressources numériques" puis médiacentre
- chercher "pix" et ensuite cliqué sur le bouton "accéder"
- une fois connecté sur pix avec l'ENT, allez dans votre compte pix puis dans "méthodes de connexion"

**Comment by ebarbier** [comment]
Merci beaucoup pour votre retour @WeeskyBDW ! Nous sommes en effet au courant de ce besoin et nous allons y rémédier bientôt. Bonne journée !

**Comment by ebarbier** [comment]
Re-bonjour @WeeskyBDW.
Cette demande d'évolution a été prise en compte et sera disponible dans la prochaine mise en prod (v3.113.0)!
Bonne journée et merci encore pour votre retour!
