### ISSUE TITLE
Linter les traductions API dans la CI

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#3570]
Le plugin eslint [eslint-plugin-i18n-json ](https://www.npmjs.com/package/eslint-plugin-i18n-json )est installé, mais pas utilisé dans la CI.

TODO:
- transformer la tâche npm ci-dessous en supprimant le --fix
 "lint:json": "eslint --fix --ext .json translations/"
- l'ajouter à la CI en la déclenchant dans `lint:code`

**Comment by yaf** [comment]
Cette PR me semble terminé (par la #3575 il manque encore un truc ?

**Comment by francois2metz** [comment]
Ca doit être bon en effet. Je ferme.
