### ISSUE TITLE
La règle `qunit/no-only` n'est pas appliquée sur pix-certif

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#3941]
https://github.com/1024pix/pix/pull/3935#discussion_r783879968

**Comment by Thomasevano** [comment]
Le problème est aussi présent dans Admin et Orga. Pour cela il faut mettre a jour `eslint-plugin-qunit` a la dernière version (7.2.0) qui prend en charge le `test.only`.
Cependant une nouvelle règle `qunit/no-assert-equal` génère de nombreuses nouvelles erreurs.
Nous déja commencer cela sur [cette branche](https://github.com/1024pix/pix/tree/fix-remove-only-in-tests)
