### ISSUE TITLE
La contrainte d'intégrité référentielle vers les badges est fragile

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#3967]
# Problème
Voir https://github.com/1024pix/pix/pull/3928
Si le `badge.partnerKey` est modifié, il est nécessaire de supprimer/recréer des FK vers plusieurs tables :scream: 

# Solution
Utiliser `badges.id` comme cible de la contrainte

**Comment by francois2metz** [comment]
cc @MathieuGilet

**Comment by francois2metz** [comment]
Une idée pourrait être que la clef primaire soit la `partnerKey` puisqu'on a une contrainte d'unicité sur celle ci. L'id séquentiel pourrait être inutile en théorie (et ca l'est peut être).

**Comment by francois2metz** [comment]
Pour autant, cela ne me parait pas fragile. Si on change des foreigns keys, on doit bien s'assurer que la relation existe.

**Comment by francois2metz** [comment]
Issue obsolète d'après #7659
