### ISSUE TITLE
Le .gitignore référence des fichiers qui ne sont pas utilisés en local

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#4036]
http://github.com/1024pix/pix/blob/dev/.gitignore#L32-L33

Exemple:
- *.sqlite3
- heapsnapshot

**Comment by tetenpapier** [comment]
ce n'est pas le but d'un fichier `.gitignore` justement ?

**Comment by octo-topi** [comment]
C'est juste, j'ai corrigé la description de l'issue
