### ISSUE TITLE
La stratégie sur CircleCi n'est pas claire

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#4067]
Il y a 2 stratégies sur CircleCI:
- aller le plus vite possible, et pour cela consommer plus de ressources (cloner le repo plusieurs fois, démarrer des app en parallèle);
- ne faire les choses qu'une seule fois pour consommer moins de ressources.

Actuellement, il semble que l'approche 1 soit celle choisie, mais dans ce cas il est possible d'aller plus loin.
En effet, les phases de test (lint + test) de chaque app (ex:`api_build_and_test`) ont pour pré-requis le job `checkout` du repository.
Ce job ne fait pas que `git checkout` + ajout au cache, mais lance aussi du lint
```
npm run lint:scripts
npm run lint:yaml
npm run test:root
```

Je propose de créer un job en plus qui s'occupe de ça, pour que le checkout ne fasse que le checkout.
Il est vrai que cela ne fait pas gagner beaucoup de temps, mais cela est plus clair.

Autre sujet: fail early. Il est possible de ne pas consommer beaucoup de ressources si on s'arrête à la première erreur, car la PR ne sera pas mergeable, charge au développeur de voir s'il y en a d'autres avant de push.
Deux pistes:
- lancer le lint de toutes les applications, et ne rien lancer d'autre si ce n'est pas fini (attention: vu le partage des configurations `eslint` à la racine + chaque app, ce ne sera pas trivial, il faudra probablement faire un `npm ci` à la racine + chaque repo)
- annuler les tests en cours dès qu'un autre sort en erreur

**Comment by francois2metz** [comment]
Ca été changé récemment, et la résolution de l'issue n'est de toute façon pas clair. Je ferme.
