### ISSUE TITLE
Le logger n'est pas testé

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix#4082]
Le logger de l'API n'est pas testé, en conséquence:
- il faut des tests manuels à chaque modification (et il y a beacoup de scénarios) sinon risque de régression sur le monitoring
- il y a des appels à chaque import du logger, qui ne servent qu'à vérifier le niveau de log

```js
[07:47:48] ERROR: ERROR logs enabled
[07:47:48] WARN: WARN logs enabled
[07:47:48] INFO: INFO logs enabled
```

Une solution: créer un test automatisé sur le logger (sur pino, pas sur l'intégration avec HapiJs)
https://github.com/1024pix/pix/commit/52a8b490f984b757d78203f813543ed78ab9a1d1

La MEJ correspondante
https://docs.google.com/presentation/d/1cV4pIRJgb6ljdUdkvM2tHmPtz8aFHZGIQlQibFXt34Q/edit#slide=id.g104b68faf85_0_79

**Comment by mickaelalibert** [comment]
Un premier travail a été fait dans le cadre de cette PR pour s'assurer que le format que nous attendons pour les logs est bien celui qui est renvoyé par hapi-pino : https://github.com/1024pix/pix/pull/4741

**Comment by francois2metz** [comment]
Je ne vois pas trop comment tester le logger facilement . C'est a peine du code.
