### ISSUE TITLE
L'automerge ne fonctionne pas si il y a trop de revues sur une PR

### ISSUE THREAD

**Issue by yannbertrand** [1024pix/pix#4435]
See https://github.com/pascalgn/automerge-action/issues/189

Ne pas oublier de rebasculer de notre fork de l'automerge https://github.com/1024pix/pix/commit/965463bb8dbda8013f1f15cc93ae445768f52cd6

à la version patchée de @pascalgn

**Comment by francois2metz** [comment]
Ca été fait.
