### ISSUE TITLE
[ADR] Documenter les décisions concernant l'architecture

### ISSUE THREAD

**Issue by sroccaserra** [1024pix/pix#480]
L'idée est de pouvoir :

- prendre des décisions concernant l'architecture facilement
- prendre des décisions qui modifient des décisions précédentes facilement
- savoir qu'une décision donnée a été modifiée ou remplacé par une décision ultérieure
- pouvoir comprendre pourquoi une décision a été prise dans le passé.

Pour ça, une pratique qui fonctionne bien est de matérialiser lesdites décisions par des fichiers texte au format Markdown, versionnés avec le code.

Chaque décision suit un formalisme simple et court, avec des images si nécessaire.

- Titre
- Contexte
- Décision
- Status (pas forcément utile, le mécanisme PR peut remplacer ce paragraphe)
- Conséquences

Voir la PR #479.

## Références

- http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions
- https://github.com/joelparkerhenderson/architecture_decision_record

**Comment by MelanieMEB** [comment]
Bonjour,

Actuellement, nos PR, notre CONTRIBUTING et d'autres fichiers sont en français. Est-ce que l'on reste sur cette langue pour les ADR ?

**Comment by sroccaserra** [comment]
Je vote pour le français dans les `.md`, c'est une doc où la clarté et la compréhension sont importants.

Et aussi pour garder l'acronyme ADR, ça permet de trouver des références plus facilement.

**Comment by sroccaserra** [comment]
Exemple :

```markdown
# 1. Enregistrer les décisions concernant l'architecture

Date : 2019-04-25

## État

Accepté

## Contexte

Sur ce projet, nous avons besoin de :

- prendre des décisions concernant l'architecture facilement
- prendre des décisions qui modifient des décisions précédentes facilement
- savoir qu'une décision donnée a été modifiée ou remplacé par une décision ultérieure
- pouvoir comprendre pourquoi une décision a été prise dans le passé

## Décision

Nous utiliserons les ADR (Architecture Decision Records), telles que [décrites par Michael Nygard](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions).

## Conséquences

Voir l'article de Michael Nygard ci-dessus. Pour un outillage léger autour des ADR, voir [adr-tools](https://github.com/npryce/adr-tools) de Nat Pryce.
```

**Comment by sroccaserra** [comment]
Exemple de remplacement d'une décision par une autre :

**docs/adr/0002-utiliser-une-base-mysql.md**

```markdown
# 2. Utiliser une base MySQL

Date : 2019-04-25

## État

Remplacé par [3. Utiliser une base Postgres](0003-utiliser-une-base-postgres.md)

## Contexte

Bla bla... on a besoin d'une BDD relationnelle... bla bla

## Décision

On utilisera une base MySQL

## Conséquences

Bla... conséquence bla
```

**docs/adr/0003-utiliser-une-base-postgres.md**

```markdown
# 3. Utiliser une base Postgres

Date : 2019-04-25

## État

Accepté

Remplace [2. Utiliser une base MySQL](0002-utiliser-une-base-mysql.md)

## Contexte

MySQL nous bloque, bla bla... Postgres c'est mieux, bla.

## Décision

On remplace MySQL par Postgres.

## Conséquences

On va enfin pouvoir faire bla... Il faut réécricre les requêtes, bla bla.
```

**Comment by sroccaserra** [comment]
Pour info j'ai créé ces exemples avec [adr-tools](https://github.com/npryce/adr-tools). C'est bien documenté, les conventions choisies sont bien, et ça gère les backlinks facilement.

Vu la simplicité des documents, on peut aussi tout faire à la main en suivant les conventions qu'on veut, celles d'adr-tools par exemple (ça évite d'avoir à chercher d'autres conventions).

**Comment by DaRiviere** [comment]
10.000 fois oui pour ta proposition !

**Comment by sroccaserra** [comment]
Ok, PR ouverte.
