### ISSUE TITLE
Comment accéder à answerId

### ISSUE THREAD

**Issue by y4aniv** [1024pix/pix#5389]
Pour la création d'un plugin pour la partie administrateur, j'aimerais savoir s'il était possible d'accéder à l'```answerId``` avant qu'une réponse est été soumise par l'utilisateur ?

**Comment by laura-bergoens** [comment]
Le modèle `Answer` représente la réponse apportée à une épreuve par l'utilisateur. Cette ressource n'existe donc pas tant que l'utilisateur n'a pas répondu. De fait, il est impossible d'accéder à l'id de la ressource avant que la réponse soit envoyée.
Dispo si il y a d'autres questions !

**Comment by MelanieMEB** [comment]
Bonjour, 

Pix est toujours à l'écoute des besoins de ses utilisateurs, n'hésitez pas à nous remonter votre besoin coté administration pour voir s'il peut être inclu dans notre roadmap.
