### ISSUE TITLE
airtable schema

### ISSUE THREAD

**Issue by gkarugi** [1024pix/pix#5469]
Bonjour! 

dans la documentation pour (github.com/1024pix/pix-editor), nous avons ce qui suit : -

Si vous parvenez à vous authentifier, mais qu'une page blanche s'affiche, cela signifie très probablement que votre schéma de base Airtable est différent de celui utilisé pour le projet Pix

Où puis-je trouver le schéma ?

Merci d'avance!

**Comment by francois2metz** [comment]
Bonjour,

Pour obtenir le schema, il faut nous contacter. Il n'y pas de façon automatisé de le créer (même si cela a changer avec la nouvelle API meta d'airtable, mais aucun effort n'a été fait pour l'utiliser encore).  
Pouvez vous envoyer un mail a dev [at] pix [dot] fr avec la demande et comprenant un email qui a un compte airtable valide. Nous ferons une copie de la base minimale et vous serez associée a celle ci.

**Comment by gkarugi** [comment]
Bonjour,

Merci pour votre réponse. Nous avons pu envoyer un e-mail à l'adresse e-mail demandée. Bien que toujours pas de réponse pour le moment. Existe-t-il un autre moyen de résoudre ce problème ?

Sincères amitiés.

**Comment by MathiasDPX** [comment]
Des nouvelles ?
