### ISSUE TITLE
[FEATURE] Générer un certificat ou un diplôme de certification Pix

### ISSUE THREAD

**Issue by rudstone** [1024pix/pix#5647]
### 🦄 Problème
Actuellement, il n'est pas possible de télécharger un certificat d'accomplissement de la certification Pix mais uniquement une attestation de certification.

### 🤖 Solution
Il serait sympathique de permettre aux étudiants et aux professionnels ayant validés leurs certifications de créer de proposer de télécharger au format PDF un certificat contenant les informations suivantes :
- Logo Pix + intitulé du diplôme
- Nom + Prénom de l'étudiant / professionnel
- Un texte générique indiquant que la personne a obtenu sa certification Pix (ex : "XXX XXX a obtenu avec succès la certification PIX"
- Date d'obtention
- Code de vérification (pour la vérification auprès de l'employeur)
- Signature de l'émetteur

### 🌈 Remarques
Plusieurs demandes orales ont déjà été énoncées et cela permettra d'être partagé plus simplement sous la forme d'un diplôme (semblable aux certifications Cisco, LinkedIn...) et ainsi faciliter le partage avec l'employeur, sur LinkedIn.

### 💯 Pour tester
Aller sur Pix partie utilisateur > Mes certifications > Sélectionner une certification > Télécharger mon certificat

**Comment by clemlatz** [comment]
Bonjour, j'ai transmis votre demande au pole produit de Pix, voici la réponse :

> Nous en avions discuté à l’époque du téléchargement de l’attestation. En fait, nous considérons que la certification est uniquement sur Pix. C’est l’affichage sur la plateforme qui fait foi. Seule une attestation est téléchargeable, qui permet d’aller vérifier en ligne la véracité des données. Ça évite notamment les histoires d’anti-falsification de documents, sur lesquelles nous nous étions cassé les dents (filigrane, impression sur papier spécial, etc.)

**Comment by rudstone** [comment]
Oui d'accord mais deux solutions afin de vérifier l'authenticité de la certification :

- Sur le diplôme : faire apparaitre un ID à faire vérifier sur la plateforme Web de Pix.
- Après avoir saisis l'ID de vérification, faire apparaitre le Checksum 256 du diplôme en PDF initial lors de la génération de celui-ci, à savoir si il a été modifié ou non par un tiers.

**Comment by clemlatz** [comment]
Le premier point existe déjà aujourd'hui, l'attestation de certification inclut un code de vérification qui, une fois entré sur la plateforme Pix, permet de ré-afficher l'attestation et donc de vérifier son authenticité.

Il me semble que cela couvre aussi le second point sans nécessiter de checksum, mais dites-moi si je me trompe.

**Comment by HEYGUL** [comment]
@rudstone Il semble que les réponses de Clément vous ont satisfait ?
Nous vous invitons à ouvrir une nouvelle issue si vous avez de nouvelles remarques.
