### ISSUE TITLE
PIX en local

### ISSUE THREAD

**Issue by y4aniv** [1024pix/pix#5674]
Bonjour,

J'ai envie de démarrer PIX en local cependant, je n'ai aucune idée comment mettre des questions. Est-il possible d'avoir les questions qui existent déjà ?

**Comment by MelanieMEB** [comment]
Bonjour, 

Il est possible d'installer Pix pour créer un nouvel outils d'évaluation, avec votre propre référentiel de compétences et de questions. 

Ce logiciel et son code source sont distribués sous [licence AGPL](https://www.gnu.org/licenses/why-affero-gpl.fr.html), mais les questions et le référentiel de compétence numérique restent la propriété de Pix.

Vous aurez donc besoin de créer votre propre référentiel de question pour votre projet de Pix en Local.

Bonne journée.
