### ISSUE TITLE
Erreur configuration PIX

### ISSUE THREAD

**Issue by JonasQuinn974** [1024pix/pix#5909]
Hello, 

à l'installation, j'ai une erreur lors de la commande "npm run configure" 

`4580 timing reifyNode:node_modules/faker Completed in 170720ms

4581 timing reifyNode:node_modules/rxjs Completed in 171039ms
4582 timing reifyNode:node_modules/@fortawesome/free-solid-svg-icons Completed in 170305ms
4583 timing reifyNode:node_modules/date-fns Completed in 180182ms
4584 timing reify:unpack Completed in 180878ms
4585 timing reify:rollback:createSparse Completed in 7153ms
4586 timing reify:rollback:retireShallow Completed in 0ms
4587 timing command:ci Completed in 212249ms
4588 verbose stack Error: process terminated
4588 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:200:39
4588 verbose stack     at process.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:53:5)
4588 verbose stack     at process.emit (node:events:513:28)
4589 verbose cwd /home/ubuntu/pix/admin
4590 verbose Linux 5.15.0-25-generic
4591 verbose node v16.19.1
4592 verbose npm  v8.19.4
4593 error process terminated
4594 error signal SIGTERM
4595 verbose exit 1
4596 timing npm Completed in 212885ms
4597 verbose unfinished npm timer reify 1680171340927
4598 verbose code 1
4599 error A complete log of this run can be found in:
4599 error     /root/.npm/_logs/2023-03-30T10_15_21_491Z-debug-0.log
`

Je suis sous ubuntu : 

` lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
`

et j'ai apparemment les éléments pour construire un bon environnement :  

`

ð Welcome to the Pix developer environment installation & configuration procedure.
The good news is that the procedure is fully automated and last less than 5 minutes!
So, please take a âï¸ and enjoy this awesome moment.
If you get bored, you can always visit our website https://pix.fr or follow us on Twitter https://twitter.com/pix_officiel ð

Verifying prerequesite programsâ¦
â
 Required programs have been found.

Generating environment config file for Pix API (api/.env)â¦
â
 api/.env file copied from api/sample.env.

Installing Pix apps dependenciesâ¦

> pix@3.327.0 preinstall
> npx check-engine

Checking versions...

â node was validated with 16.
â npm was validated with >=8.13.2 <9.

 Environment looks good!
`

Quelqu'un aurait une idée ?

**Comment by francois2metz** [comment]
Bonjour @JonasQuinn974. 
Je ne vois pas ce qui aurait pu ne pas marcher dans les logs. Pouvez vous partager le contenu du fichier `/root/.npm/_logs/2023-03-30T10_15_21_491Z-debug-0.log` pour que l'on puisse en savoir plus?

**Comment by JonasQuinn974** [comment]
[2023-03-30T10_15_21_491Z-debug-0.log](https://github.com/1024pix/pix/files/11197946/2023-03-30T10_15_21_491Z-debug-0.log)
voilà le fichier

**Comment by francois2metz** [comment]
Est ce que vous avez réessayer ? C'est comme si le processus avait été tué par quelque chose d'autre.

**Comment by JonasQuinn974** [comment]
oui j'ai essayé plusieurs fois. Et c'est toujours au même endroit que le processus s'arrête et quitte.

**Comment by JonasQuinn974** [comment]
Bonjour,

J'ai trouvé la source du problème. J'ai un serveur avec 4Go de RAM sans SWAP. 
J'ai ajouté des sondes sur mon serveur et cela m'a permis d'identifier un problème de mémoire vive.
La commande "npm run configure" sature la mémoire et le processus est arrêté.

J'ai ajouté un SWAP à mon serveur et le processus est allé jusqu'à son terme.

**Comment by francois2metz** [comment]
Merci du retour!
