### ISSUE TITLE
[BUG] remplissage automatique formulaire d'inscription sur Google chrome

### ISSUE THREAD

**Issue by MaximeAmore** [1024pix/pix#5943]
Hello 

J'ai tenté de m'inscrire sur le site via ce lien: https://app.pix.fr/inscription

Après avoir rentré mes coordonnées via le remplissage automatique de google chrome, et appuyé sur le bouton "Je m'inscris", le formulaire ne semble pas s'envoyer et le bouton est bloqué en mode "loading"

<img width="574" alt="image" src="https://user-images.githubusercontent.com/16916956/230436273-800f9471-4225-4dc5-ae76-df3652875f2b.png">

![image](https://user-images.githubusercontent.com/16916956/230436694-0e7e816c-2094-4166-9c61-f575d8007e14.png)

Le remplissage automatique ne suffit pas au formulaire qui m'indique que je n'ai pas écrit mon nom. 

<img width="506" alt="image" src="https://user-images.githubusercontent.com/16916956/230437904-95deb251-2e37-4f8f-8968-6f561ee0b152.png">

A ce moment là, dans la fonction `signup` dans `this.args.user` `lastName` et `email` sont vides. 

Le fait de focus l'input fait disparaitre le message d'erreur (à ce moment on peut valider le formulaire).
À noter qu'à ce moment là je n'ai pas d'erreur concernant l'adresse mail (d'où le message d'erreur ci-dessus: le formulaire est considéré comme valide après avoir focus l'input `lastName`, mais au moment de l'envoyer `email` est vide) 

Du coup il faudrait voir au niveau du composant PixInput on peut prévoir ce cas de figure

OS: MacOS 12.4 
Navigateur: Google Chrome Version 111.0.5563.146

**Comment by francois2metz** [comment]
Bonjour Maxime, merci pour le rapport de bug.

La validation se fait sur le focusout, dans ce cas c'est clair que ca ne fonctionnera pas.
