### ISSUE TITLE
Le cas CertificationCourse

### ISSUE THREAD

**Issue by laura-bergoens** [1024pix/pix#670]
Contexte
--------

Le modèle et l'usage de _certificationCourse_ dans le code et dans la base sont pour le moins discutable et très certainement sujets à réflexion et refacto. En se penchant sur son cas, on trouve des incohérences au niveau de sa présence 'étrangère' dans d'autres tables, ses responsabilités et ses données sont floues dans le code.
Cette issue se propose de lister l'ensemble des problèmes liés à _certificationCourse_, afin de faciliter et d'encourager l'amélioration et le refacto de cet ensemble atomiquement, pierre après pierre, baby steps.
Je propose aussi qu'idéalement ce genre de révisions et améliorations reviennent à la team #Certif ( :rocket: ) histoire d'approfondir davantage la connaissance de notre domaine, mais en revanche j'encourage l'ensemble de l'équipe à mettre en évidence les points de douleur existants autour de _certificationCourse_.

Issue initiée à partir d'une discussion autour d'une PR dont la branche a été fermée :
https://github.com/1024pix/pix/pull/668

TL;DR : Alimentez la liste de problèmes liés à _certificationCourse_, tenter de les résoudre le plus atomiquement possible au fur et à mesure.

Sujets
-----------
- Remettre à plat le nommage afin de faciliter les différentes "magies" des outils utilisés (Bookshelf, JSONApi, Ember) mais aussi la lisibilité. En effet, on remarque par exemple que les _certificationCourses_ sont appelées _certifications_ dans le modèle domaine de _session_. 
- Casser en plusieurs morceaux les usages de certificationCourse. On pense notamment à son usage via les _assessments_ : dans la table, _certificationCourseId_ n'est en fait PAS toujours une clé étrangère vers un _certificationCourse_, mais peut être une chaîne contenant 'DEMO' par exemple, ou une information du référentiel....
- Définir les données de _certificationCourse_, et voir si des modifications du schéma de la table sont aussi nécessaires, particulièrement concernant les champs du modèle suivants : _assessment_, _type_, _challenges_, _nbChallenges_
- Statuer sur l'utilité du champ _updatedAt_ dans la table

**Comment by jonathanperret** [comment]
> * Remettre à plat le nommage afin de faciliter les différentes "magies" des outils utilisés (Bookshelf, JSONApi, Ember) mais aussi la lisibilité. En effet, on remarque par exemple que les _certificationCourses_ sont appelées _certifications_ dans le modèle domaine de _session_.

Oui, la table `certification-courses` désigne à la fois :
 * la liste des questions à poser (ce qui est appelé _course_, ou en français et dans Airtable _test_) lors d'un examen de certification ;
 * le diplôme lui-même.

> * Casser en plusieurs morceaux les usages de certificationCourse. On pense notamment à son usage via les _assessments_ : dans la table, _certificationCourseId_ n'est en fait PAS toujours une clé étrangère vers un _certificationCourse_, mais peut être une chaîne contenant 'DEMO' par exemple, ou une information du référentiel....

Attention il n'y a justement _pas_ de colonne `certificationCourseId` dans la table `assessments`. Il y a une colonne `courseId` qui dans l'intention désigne "la liste des questions à poser pour cet _assessment_" et peut contenir :
 * l'identifiant Airtable (chaîne `recXXXXXXXXX`) d'un _course_ de démo : liste statique de questions (la chaîne `DEMO` n'est jamais mise dans la colonne `courseId`) ;
 * l'identifiant Airtable (chaîne `recXXXXXXXXX`) d'un _course_ **adaptatif** : utilisé jusqu'à récemment pour les _assessments_ V1 (`PLACEMENT`) pour déclencher le choix de questions par l'algorithme CAT ;
 * un entier faisant référence à la clé primaire de la table `certification-courses`, signifiant que la liste des questions à poser doit être celle des `certification-challenges` associés à cette ligne de `certification-courses` ;
 * pour les _assessments_ de type `SMART_PLACEMENT` et `COMPETENCE_EVALUATION`, une chaîne est utilisée qui ne fait référence à aucun enregistrement.
 * pour les _assessments_ de type `PREVIEW` par le passé on générait un `courseId` aléatoire sous la forme `null<uuid>` mais à présent on stocke un `courseId` `null`.

La réutilisation de cette colonne pour pointer alternativement vers des enregistrements Airtable et des lignes d'une table locale présentait à l'époque l'avantage de n'utiliser qu'une colonne pour représenter le concept de "liste de questions à poser" dans tous les cas, mais notamment l'inconvénient d'empêcher l'utilisation des règles d'intégrité référentielle (contrainte de clé étrangère) de la base donnée.

Je pense qu'on peut aujourd'hui rationaliser l'utilisation de la colonne `assessments.courseId` de la façon suivante :
 * réserver l'utilisation de `courseId` aux seuls _assessments_ pour lesquels cette information est encore pertinente à savoir les `DEMO` ;
 * pour éviter une perte d'information tout en rendant la base cohérente, migrer les anciens _assessments_ de type `PLACEMENT` en mettant à `null` la colonne `courseId` mais en alimentant `competenceId` avec l'identifiant de compétence correspondant ;
 * stocker `null` dans `courseId` pour les `SMART_PLACEMENT` et `COMPETENCE_EVALUATION` ;
 * créer une colonne `certificationCourseId`, référençant la colonne `certification-courses.id` et utilisée uniquement par les _assessments_ de type `CERTIFICATION`.

> * Statuer sur l'utilité du champ _updatedAt_ dans la table

Je propose la règle suivante : si les données d'une table sont modifiées par l'application, mettre `createdAt` et `updatedAt` ; sinon juste `createdAt`.

**Comment by sroccaserra** [comment]
Un CertifiationCourse regroupe les principes de :
- certificat
- participation à une session
- identité réelle vérifiée par le surveillant (nom, prénom, date de naissance)
- liste de questions pour un utilisateur
