### ISSUE TITLE
Mise à jour de nos libs coeur (Hapi.js, Ember.js et Ember Data)

### ISSUE THREAD

**Issue by sroccaserra** [1024pix/pix#688]
Salut @1024pix/dev, point sur les versions de nos libs coeur :

- _Hapi.js_ date de février (17.8.4),
- _Ember.js_ date du mois d’avril et n’est pas LTS (3.9.1)
- _Ember Data_ date de mai (3.9.3)

Les versions actuelles de ces libs sont respectivement 18.3.2, 3.12.0, et 3.10.

Quand et comment est-ce qu'on les met à jour ?

## Références

- https://hapi.dev/resources/changelog/
- https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md
- https://github.com/emberjs/data/blob/master/CHANGELOG.md

**Comment by laura-bergoens** [comment]
Ce serait bien de prendre un peu de temps, car comme on le sait tous plus on attend plus c'est douloureux.

**Comment by jonathanperret** [comment]
`knex` et `bookshelf` aussi…

**Comment by laura-bergoens** [comment]
Voici quelque chose côté API
https://github.com/1024pix/pix/pull/694

**Comment by laura-bergoens** [comment]
Je me permets de fermer l'issue, elle a été traitée selon plusieurs PR depuis.
