### ISSUE TITLE
Lien cassé sur le README

### ISSUE THREAD

**Issue by Ruff9** [1024pix/pix#743]
Sur votre README, on peut trouver la phrase suivante : 

"Pour récupérer les différents identifiants / clés de connexion, s'adresser à un membre de l'équipe PIX."

Le lien ancré sur "l'équipe PIX" me renvoie une erreur 404.

Soit vous avez changé le nom de la team, soit accéder à cette page nécessite une autorisation spécifique.

**Comment by laura-bergoens** [comment]
Bonsoir @Ruff9 ,
Merci pour l'info, on s'occupe de corriger l'erreur rapidement.

**Comment by Ruff9** [comment]
Je viens de réessayer, et malgré le changement de lien, le problème persiste.

![Screen Shot 2019-10-18 at 3 57 58 PM](https://user-images.githubusercontent.com/5736823/67124288-4418c680-f1c0-11e9-8ef8-874a370c8b9f.png)

Cela ressemble beaucoup à un problème d'autorisation : J'ai l'impression qu'il faut faire partie de votre équipe pour voir cette page. C'est étonnant : ce projet est public, donc j'imagine que vous souhaitez que des personnes extérieures proposent des modifications. 

Lancer l'application en local me permettrais de l'étudier, pour voir si je peux proposer des PR.

**Comment by dherault** [comment]
Fixé, merci pour l'issue @Ruff9. Dans le futur nous aurons peut être une page d'équipe avec des liens permettant de nous contacter. Au plaisir de vous revoir.
