### ISSUE TITLE
Proposition : Création d'un service unique pour la génération des keys/codes

### ISSUE THREAD

**Issue by chrc** [1024pix/pix#765]
Dans l'api, à différents endroits des keys ou codes sont génénés, par exemple :
  * api/lib/domain/services/campaigns/campaign-code-generator.js
  * api/lib/domain/usecases/create-organization-invitation.js

Je propose de créer une unique service pour ces genérations.

**Comment by francois2metz** [comment]
Il y a un un service code-generator qui a l'air de faire ça. Les anciens liens n'ont plus l'air pertinent. On ferme.
