### ISSUE TITLE
Proposition : Séparation des concepts Key, TemporaryKey, Code et Token

### ISSUE THREAD

**Issue by chrc** [1024pix/pix#766]
Dans l'api, il y une confusion entre générer un token, une key, une temporaryKey et un code.
Par exemple :
* api/lib/domain/services/reset-password-service.js
* api/lib/domain/services/token-service.js

Je propose de renommer les fonctions en conséquence.

**Comment by octo-topi** [comment]
Vu les récents développements, est-ce toujours d'actualité ?
