### ISSUE TITLE
Bug mineur - sur la page d'accueil bouton Commencer un test

### ISSUE THREAD

**Issue by Lamisedaxeh** [1024pix/pix#806]
Petit bug chez moi et un ami quand l'on appuie sur le bouton "Commencer" *(voir image ci-dessous)* pour le test sur la page d'accueil.
> https://pix.fr/

![image](https://user-images.githubusercontent.com/37446510/68091582-cb815d80-fe81-11e9-9321-30a6d5d9e568.png)
Qui redirige vers ce lien mal formé : 
 > `http://pix.fr/function link() { [native code] }`

Voilà le résultat : 
![image](https://user-images.githubusercontent.com/37446510/68091634-519da400-fe82-11e9-8ae1-8ef17defa3f6.png)

**Comment by jonathanperret** [comment]
Bonjour @Lamisedaxeh , merci pour ce signalement. Le lien a été corrigé dans https://github.com/1024pix/pix-site/pull/84 et le site a été redéployé.
