### ISSUE TITLE
Aide à la configuration du projet

### ISSUE THREAD

**Issue by RucaSantos** [1024pix/pix#907]
Bonjour

Je me permets de vous écrire car j'ai besoin d'aide en ce qui concerne l'utilisation de votre plateforme de certification.

Nous essayons de développer un projet pour évaluer les compétences numériques des étudiants, et le projet pix semblait être un bon moyen, mais nous avons du mal à le mettre en service.

Nous avons réussi à compiler et à exécuter le projet. Avec l'utilisation de "AUTH_SECRET = toto" (https://github.com/1024pix/pix/issues/299), nous avons pu effectuer des connexions dans les 4 pages, créer de nouveaux utilisateurs et organisations, mais nous n'avons pas réussi à obtenir un test réel en cours. Nous n'avons également pas pu utiliser pleinement l'API en raison de problèmes d'authentification.

Le fil a mentionné que nous devrions vous contacter pour développer le projet et accéder à la base de connaissances. Comment devons-nous procéder?

Merci d'avance,

Rui Santos

**Comment by jbuget** [comment]
Bonjour @RucaSantos,

Merci de votre intérêt pour le projet Pix.

Nous sommes biens conscients qu'il est très difficile aujourd'hui d'installer et d'exécuter la plateforme en autonomie.

Nous envisageons, à terme, de simplifier l'exécution et l'hébergement ad-hoc de la solution. Il s'agit d'un investissement stratégique en cours de priorisation.

D'ici là, nous devons mettre à jour la documentation pour éclaircir ce point et nous montrer toujours plus transparents.

Nous vous tiendrons informés dès que nous aurons suffisamment avancés sur le sujet.
