### ISSUE TITLE
[Tests] Lancer les tests dans le bon ordre.

### ISSUE THREAD

**Issue by dherault** [1024pix/pix#978]
Actuellement les tests de l'API et des applications s'exécutent dans cet ordre : acceptance, integration, unitaires.

Le bon ordre serait : unitaire, integration, acceptance.

A voir en point tech.

**Comment by laura-bergoens** [comment]
@dherault Comment savoir quel est le bon ordre? Qu'est ce que bon ordre signifie ici ?
